
ALTER PROCEDURE [dbo].[PRC_POLIZAS_POR_TRASPASAR_CXP_DET] (@ANIO INT,@MES INT, @FECHA VARCHAR(15),@CONSILIADO INT, @SITE_ID VARCHAR(15))
AS

	SET NOCOUNT ON;
  CREATE TABLE #POLIZASCXP(	 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO INT,
    VAT_GL_ACCT_ID VARCHAR(30),
    DESCRIPCION VARCHAR(200),
    TRASLADO VARCHAR(30),
    TC_FACTURA DECIMAL(15,8),
    TC_DEPOSITO DECIMAL(15,8),    
    IVA_MXN_TRASLADAR_FACT DECIMAL(15,2),
    IVA_MXN_TRASLADAR_DEP DECIMAL(15,2),
    RET_MXN_TRASLADAR_FACT DECIMAL(15,2),
    RET_MXN_TRASLADAR_DEP DECIMAL(15,2),
    PERDIDA_GANANCIA DECIMAL(15,2),
    CUENTA_PER_GANANCIA VARCHAR(30),
    FECHA VARCHAR(10),
    CLIENTE VARCHAR(120),
    SITE_ID VARCHAR(15),
    VOUCHER VARCHAR(15),
    VOUCHER_LN VARCHAR(10),
    RFC VARCHAR(25),
    NAME VARCHAR(50),
    AMOUNT DECIMAL(15,2),
    INVOICE_ID VARCHAR(15),
    PAYMENT_NO INT
    );

	CREATE TABLE #POLIZASNEGATIVAS( 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO INT,
    SITE_ID VARCHAR(15));
	
	IF (@CONSILIADO = 1)
	BEGIN
		-- Obtener todos los movimientos consiliados		
		INSERT #POLIZASCXP(SITE_ID, BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, IVA_MXN_TRASLADAR_FACT,RET_MXN_TRASLADAR_FACT, TC_DEPOSITO, IVA_MXN_TRASLADAR_DEP, RET_MXN_TRASLADAR_DEP,PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE
			,VOUCHER,VOUCHER_LN,RFC,NAME,AMOUNT,INVOICE_ID,PAYMENT_NO)
			SELECT A.SITE_ID
				, A.BANK_ACCOUNT_ID 
				,A.CONTROL_NO 
				,A.VAT_GL_ACCT_ID
				,B.DESCRIPCION
				,B.TRASLADO
				,A.TC_FACTURA
				-- Hacer cero el monto, cuando el Monto de IVA prorrateado sea un centavo positivo o negativo.
				,CASE 
					WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = 0.01 THEN 0 
					WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = -0.01 THEN 0 
				ELSE SUM(A.IVA_TRASLADO_MXN_FACT)  END
				,0
				,A.TC_Pago				
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN A.IVA_TRASLADO_MXN_PAGO + 0.01
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN A.IVA_TRASLADO_MXN_PAGO - 0.01
				ELSE SUM(A.IVA_TRASLADO_MXN_PAGO) END AS IVA_MXN_TRASLADAR_DEP	
				,0
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN 0 
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN 0 
				ELSE SUM(A.GANANCIA_PERDIDA)END
				,A.CUENTA_PER_GANANCIA
				,@FECHA
				,A.VENDOR_ID
				,A.VOUCHER_ID
				,A.LINE_NO
				,isnull(V.VAT_REGISTRATION,'')
				,V.NAME
				,A.AMOUNT
				,A.INVOICE_ID
				,A.PAYMENT_NO
			FROM VMX_DIOTCUENTAS AS b,VMX_IVA_TRASL_CXP_02 AS a --CASH_DISBURSE
			INNER JOIN VENDOR V ON V.ID = A.VENDOR_ID
			WHERE b.Cuenta =  a.VAT_GL_ACCT_ID
				AND b.Estado = 'True'
				AND a.ANIO_CONCILIACION = @ANIO
				AND a.MES_CONCILIACION = @MES	
				AND a.SITE_ID = @SITE_ID			
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO,a.VAT_GL_ACCT_ID,b.Descripcion,a.TC_FACTURA,b.Traslado,A.IVA_TRASLADO_MXN_FACT,
				A.TC_Pago,A.IVA_TRASLADO_MXN_PAGO,A.GANANCIA_PERDIDA,A.CUENTA_PER_GANANCIA,a.VENDOR_ID
				,A.VOUCHER_ID
				,A.LINE_NO
				,V.VAT_REGISTRATION
				,V.NAME
				,AMOUNT
				,A.INVOICE_ID
				,A.PAYMENT_NO
				
			-- Obtener los movimientos con montos negativos
			INSERT #POLIZASNEGATIVAS(SITE_ID,BANK_ACCOUNT_ID,CONTROL_NO)
				SELECT A.SITE_ID, A.BANK_ACCOUNT_ID,A.CONTROL_NO      
				FROM VMX_IVA_TRASL_CXP_02 AS a,VMX_DIOTCUENTAS AS b 
				WHERE b.Cuenta =  a.VAT_GL_ACCT_ID AND b.Estado = 'True' 
					-- Consiliados
					AND a.ANIO_CONCILIACION = @ANIO AND a.MES_CONCILIACION = @MES AND a.SITE_ID = @SITE_ID
				GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO	,a.VAT_GL_ACCT_ID        
				HAVING CASE WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = 0.01 THEN 0 WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = -0.01 THEN 0 ELSE SUM(A.IVA_TRASLADO_MXN_FACT)END < 0
	END
	ELSE
	BEGIN
		-- Obtener todos los movimientos consiliados y no consiliados
		INSERT #POLIZASCXP(SITE_ID, BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, IVA_MXN_TRASLADAR_FACT, RET_MXN_TRASLADAR_FACT,TC_DEPOSITO, IVA_MXN_TRASLADAR_DEP,RET_MXN_TRASLADAR_DEP, PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE
			,VOUCHER,VOUCHER_LN,RFC,NAME,AMOUNT,INVOICE_ID,A.PAYMENT_NO)
			SELECT A.SITE_ID
				,A.BANK_ACCOUNT_ID 
				,A.CONTROL_NO 
				,A.VAT_GL_ACCT_ID
				,B.DESCRIPCION
				,B.TRASLADO
				,A.TC_FACTURA
				-- Hacer cero el monto, cuando el Monto de IVA prorrateado sea un centavo positivo o negativo.
				,CASE 
					WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = 0.01 THEN 0 
					WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = -0.01 THEN 0 
				ELSE SUM(A.IVA_TRASLADO_MXN_FACT)  END
				,0
				,A.TC_Pago				
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN A.IVA_TRASLADO_MXN_PAGO + 0.01
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN A.IVA_TRASLADO_MXN_PAGO - 0.01
				ELSE SUM(A.IVA_TRASLADO_MXN_PAGO) END AS IVA_MXN_TRASLADAR_DEP	
				,0
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN 0 
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN 0 
				ELSE SUM(A.GANANCIA_PERDIDA)END
				,A.CUENTA_PER_GANANCIA
				,@FECHA
				,A.VENDOR_ID
				,A.VOUCHER_ID
				,A.LINE_NO
				,isnull(V.VAT_REGISTRATION,'')
				,V.NAME
				,A.AMOUNT
				,A.INVOICE_ID
				,A.PAYMENT_NO
			FROM VMX_DIOTCUENTAS AS b,VMX_IVA_TRASL_CXP_02 AS a --CASH_DISBURSE
			INNER JOIN VENDOR V ON V.ID = A.VENDOR_ID
			WHERE b.Cuenta =  a.VAT_GL_ACCT_ID
				AND b.Estado = 'True'
				AND a.ANIO_POSTEO = @ANIO
				AND a.MES_POSTEO = @MES
				AND a.SITE_ID = @SITE_ID
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO,a.VAT_GL_ACCT_ID,b.Descripcion,a.TC_FACTURA,b.Traslado,A.IVA_TRASLADO_MXN_FACT,
				A.TC_Pago,A.IVA_TRASLADO_MXN_PAGO,A.GANANCIA_PERDIDA,A.CUENTA_PER_GANANCIA,a.VENDOR_ID
				,A.VOUCHER_ID
				,A.LINE_NO
				,V.VAT_REGISTRATION
				,V.NAME
				,AMOUNT
				,A.INVOICE_ID
				,A.PAYMENT_NO
		
		-- Obtener los movimientos con montos negativos
		INSERT #POLIZASNEGATIVAS(SITE_ID, BANK_ACCOUNT_ID,CONTROL_NO)
			SELECT A.SITE_ID, A.BANK_ACCOUNT_ID,A.CONTROL_NO      
			FROM VMX_IVA_TRASL_CXP_02 AS a,VMX_DIOTCUENTAS AS b --CASH_DISBURSE
			WHERE b.Cuenta =  a.VAT_GL_ACCT_ID AND b.Estado = 'True' 
				-- No Consiliados
				AND a.ANIO_POSTEO = @ANIO AND a.MES_POSTEO = @MES AND a.SITE_ID = @SITE_ID
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO	,a.VAT_GL_ACCT_ID        
			HAVING CASE WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = 0.01 THEN 0 WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = -0.01 THEN 0 ELSE SUM(A.IVA_TRASLADO_MXN_FACT)END < 0
	END		
    
    -- Eliminar las polizas negativas. Filtrar por Banco y No. Control                        
	DELETE FROM #POLIZASCXP 
	FROM #POLIZASCXP AS P LEFT JOIN #POLIZASNEGATIVAS AS N ON P.BANK_ACCOUNT_ID = N.BANK_ACCOUNT_ID AND P.CONTROL_NO = N.CONTROL_NO AND P.SITE_ID = N.SITE_ID
	WHERE N.BANK_ACCOUNT_ID IS NOT NULL AND N.CONTROL_NO IS NOT NULL
	
	-- Eliminar las polizas que han completado el traspaso de IVA.
	DELETE FROM #POLIZASCXP
	FROM #POLIZASCXP AS P 
		LEFT JOIN VMX_CONTOLPOLIZA_LINE AS PL 
			ON P.BANK_ACCOUNT_ID = PL.BANK_ACCOUNT_ID AND P.CONTROL_NO = PL.CONTROL_NO AND P.VAT_GL_ACCT_ID = PL.CUENTA AND P.SITE_ID = PL.SITE_ID AND PL.CUSTOMER_ID = P.CLIENTE
	WHERE PL.BANK_ACCOUNT_ID IS NOT NULL AND PL.CONTROL_NO IS NOT NULL AND PL.CUENTA IS NOT NULL
		AND PL.TIPO_OPERACION = 'CXP'
	
	SELECT SITE_ID
		,BANK_ACCOUNT_ID AS Banco
		,CONTROL_NO AS "No. Control"
		,CLIENTE AS Proveedor
		,RFC AS "RFC"
		,NAME AS "Nombre Proveedor"
		,VAT_GL_ACCT_ID AS Cuenta
		,DESCRIPCION AS "Descripción"
		,TRASLADO AS "Cuenta Traslado"
		,VOUCHER AS Voucher
		,VOUCHER_LN AS "Linea Voucher"
		,INVOICE_ID AS Factura
		,AMOUNT AS Monto
		,TC_FACTURA AS "Tipo Cambio Factura"
		,TC_DEPOSITO AS "Tipo Cambio Deposito"
		,ISNULL(IVA_MXN_TRASLADAR_FACT,0.0) AS "IVA Factura"
		,ISNULL(IVA_MXN_TRASLADAR_DEP,0.0) AS "IVA Deposito"
		,ISNULL(RET_MXN_TRASLADAR_FACT,0.0) AS "Retención Factura"
		,ISNULL(RET_MXN_TRASLADAR_DEP,0.0) AS "Retención Deposito"
		,ISNULL(PERDIDA_GANANCIA,0.0) AS "Perdida Ganancia"
		,CUENTA_PER_GANANCIA AS "Cuenta Perdida Ganancia"
		,FECHA AS Fecha
		,PAYMENT_NO "Payment No"

	FROM #POLIZASCXP 
	ORDER BY BANK_ACCOUNT_ID,CONTROL_NO,VOUCHER,VOUCHER_LN

	DROP TABLE #POLIZASCXP                    
	DROP TABLE #POLIZASNEGATIVAS


