
ALTER VIEW [dbo].[VMX_IVA_CXC_01]
AS
SELECT  CRL.SITE_ID, CRL.CUSTOMER_ID AS Cod_Cliente, CRL.INVOICE_ID AS Factura, 
		SUM(CRL.PCURR_AMOUNT) AS Monto_Deposito, -- Monto del depósito en moneda del pago/deposito
		SUM(CRL.AMOUNT) AS Monto_Deposito2, -- Monto del depósito en moneda nativa de la entidad
		CR.STATUS AS Estatus,
        (SELECT CURRENCY_ID FROM dbo.RECEIVABLE WHERE (INVOICE_ID = CRL.INVOICE_ID)) moneda_factura,
		CR.CURRENCY_ID Moneda_Deposito, --moneda del pago/deposito
		CRC.SELL_RATE AS TC_Deposito, --tipo de cambio del pago/deposito
		--CR.SELL_RATE AS TC_Deposito2, --tipo de cambio del pago/deposito
        CR.DEPOSIT_ID AS Cod_Deposito, 
		YEAR(BD.CLEARED_DATE) AS Anio_Conc, 
		MONTH(BD.CLEARED_DATE) AS Mes_Conc, 
        CR.CHECK_ID, CR.BANK_ACCOUNT_ID, 
		MONTH(CR.POSTING_DATE) AS MES_POSTEO, 
		YEAR(CR.POSTING_DATE) AS ANIO_POSTEO,
		CR.CHECK_DATE FECHA_PAGO
FROM    dbo.CASH_RECEIPT AS CR 
INNER JOIN dbo.CASH_RECEIPT_LINE AS CRL ON CR.CUSTOMER_ID = CRL.CUSTOMER_ID AND CR.CHECK_ID = CRL.CHECK_ID 
INNER JOIN dbo.BANK_DEPOSIT AS BD ON CR.BANK_ACCOUNT_ID = BD.BANK_ACCOUNT_ID AND CR.DEPOSIT_ID = BD.DEPOSIT_ID 
INNER JOIN dbo.CASH_RECEIPT_CURR AS CRC ON CR.CUSTOMER_ID = CRC.CUSTOMER_ID AND CR.CHECK_ID = CRC.CHECK_ID AND CR.CURRENCY_ID = CRC.CURRENCY_ID
WHERE     (CRL.GL_ACCOUNT_ID IS NULL)
GROUP BY CRL.CUSTOMER_ID, CRL.INVOICE_ID, CR.STATUS, CRC.SELL_RATE, CR.DEPOSIT_ID, CR.CURRENCY_ID, YEAR(BD.CLEARED_DATE), MONTH(BD.CLEARED_DATE),
         CR.CHECK_ID, CR.BANK_ACCOUNT_ID, CR.POSTING_DATE, CR.SELL_RATE, CRL.SITE_ID,CR.CHECK_DATE
HAVING (CR.STATUS <> 'X')




GO
