-- [VMX_IVA_TRASL_CXP_01]
IF EXISTS(SELECT * FROM sys.views WHERE name = 'VMX_IVA_TRASL_CXP_01' AND schema_id = SCHEMA_ID('dbo'))
     DROP VIEW VMX_IVA_TRASL_CXP_01
GO

CREATE VIEW [dbo].[VMX_IVA_TRASL_CXP_01]
AS
SELECT     CDL.SITE_ID, CDL.BANK_ACCOUNT_ID, CDL.CONTROL_NO, CD.VENDOR_ID, CD.CHECK_NO, CDL.PCURR_AMOUNT AS Monto_Pago, CDL.AMOUNT AS Monto_Pago2, 
                      CDC.SELL_RATE AS TC_Pago, CDL.SELL_RATE AS TC_Pago2, CD.CURRENCY_ID, CDL.VOUCHER_ID, CD.CLEARED, YEAR(CD.CLEARED_DATE) 
                      AS ANIO_CONCILIACION, MONTH(CD.CLEARED_DATE) AS MES_CONCILIACION, YEAR(CD.POSTING_DATE) AS ANIO_POSTEO, MONTH(CD.POSTING_DATE) 
                      AS MES_POSTEO
FROM         dbo.CASH_DISBURSE_LINE AS CDL INNER JOIN
                      dbo.CASH_DISBURSEMENT AS CD ON CDL.BANK_ACCOUNT_ID = CD.BANK_ACCOUNT_ID AND CDL.CONTROL_NO = CD.CONTROL_NO INNER JOIN
                      dbo.CASH_DISBURSE_CURR AS CDC ON CD.BANK_ACCOUNT_ID = CDC.BANK_ACCOUNT_ID AND CD.CONTROL_NO = CDC.CONTROL_NO AND 
                      CD.CURRENCY_ID = CDC.CURRENCY_ID
WHERE     (CDL.VOUCHER_ID IS NOT NULL) AND (CD.STATUS <> 'X')
GO

-- [VMX_IVA_TRASL_CXP_02]
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VMX_IVA_TRASL_CXP_02]'))
	DROP VIEW [dbo].[VMX_IVA_TRASL_CXP_02]
GO

CREATE VIEW [dbo].[VMX_IVA_TRASL_CXP_02]
AS
SELECT     VMX.SITE_ID, VMX.BANK_ACCOUNT_ID, VMX.CONTROL_NO, VMX.VENDOR_ID, VMX.CHECK_NO, VMX.Monto_Pago, VMX.TC_Pago, VMX.CURRENCY_ID, 
                      VMX.VOUCHER_ID, VMX.CLEARED, VMX.ANIO_CONCILIACION, VMX.MES_CONCILIACION, PL.LINE_NO, PL.VAT_AMOUNT, PL.VAT_GL_ACCT_ID, P.TOTAL_AMOUNT, 
                      P.SELL_RATE AS TC_FACTURA, CASE WHEN P.TOTAL_AMOUNT = 0 THEN 0 ELSE ROUND(VMX.TC_PAGO / P.TOTAL_AMOUNT, 3, 0) END AS PORC_PAGO, 
                      CASE WHEN P.TOTAL_AMOUNT = 0 THEN 0 ELSE ROUND(VMX.TC_PAGO / P.TOTAL_AMOUNT * PL.VAT_AMOUNT, 3, 0) END AS IVA_TRASLADO_NATIVO, 
                      ROUND(VMX.Monto_Pago2 / P.TOTAL_AMOUNT * PL.VAT_AMOUNT * P.SELL_RATE, 2, 0) AS IVA_TRASLADO_MXN_FACT, 
                      ROUND(VMX.Monto_Pago / P.TOTAL_AMOUNT * PL.VAT_AMOUNT * VMX.TC_Pago, 2, 0) AS IVA_TRASLADO_MXN_PAGO, 
                      ROUND(VMX.Monto_Pago2 / P.TOTAL_AMOUNT * PL.VAT_AMOUNT * P.SELL_RATE, 2, 0) 
                      - ROUND(VMX.Monto_Pago / P.TOTAL_AMOUNT * PL.VAT_AMOUNT * VMX.TC_Pago, 2, 0) AS GANANCIA_PERDIDA, 
                      CASE WHEN ROUND(VMX.Monto_Pago2 / P.TOTAL_AMOUNT * PL.VAT_AMOUNT * P.SELL_RATE, 2, 0) 
                      - ROUND(VMX.Monto_Pago / P.TOTAL_AMOUNT * PL.VAT_AMOUNT * VMX.TC_Pago, 2, 0) < 0 THEN
                          (SELECT     GL_ACCOUNT_ID
                            FROM          GL_INTERFACE_ACCT
                            WHERE      (INTERFACE_ID = 'REALIZED_LOSS') AND (SITE_ID = P.SITE_ID)) ELSE
                          (SELECT     GL_ACCOUNT_ID
                            FROM          GL_INTERFACE_ACCT
                            WHERE      (INTERFACE_ID = 'REALIZED_GAIN') AND (SITE_ID = P.SITE_ID)) END AS CUENTA_PER_GANANCIA, VMX.ANIO_POSTEO, VMX.MES_POSTEO
FROM         dbo.VMX_IVA_TRASL_CXP_01 AS VMX INNER JOIN
                      dbo.PAYABLE AS P ON VMX.VOUCHER_ID = P.VOUCHER_ID AND VMX.SITE_ID = P.SITE_ID INNER JOIN
                      dbo.PAYABLE_LINE AS PL ON P.VOUCHER_ID = PL.VOUCHER_ID

GO

-- VMX_IVA_CXC_01

IF EXISTS(SELECT * FROM sys.views WHERE name = 'VMX_IVA_CXC_01' AND schema_id = SCHEMA_ID('dbo'))
     DROP VIEW dbo.VMX_IVA_CXC_01
GO

CREATE VIEW [dbo].[VMX_IVA_CXC_01]
AS
SELECT     CRL.SITE_ID, CRL.CUSTOMER_ID AS Cod_Cliente, CRL.INVOICE_ID AS Factura, SUM(CRL.PCURR_AMOUNT) AS Monto_Deposito, SUM(CRL.AMOUNT) 
                      AS Monto_Deposito2, CR.STATUS AS Estatus,
                          (SELECT     CURRENCY_ID
                            FROM          dbo.RECEIVABLE
                            WHERE      (INVOICE_ID = CRL.INVOICE_ID)) AS Expr1, CR.CURRENCY_ID, CRC.SELL_RATE AS TC_Deposito, CR.SELL_RATE AS TC_Deposito2, 
                      CR.DEPOSIT_ID AS Cod_Deposito, CR.CURRENCY_ID AS Moneda_Deposito, YEAR(BD.CLEARED_DATE) AS Anio_Conc, MONTH(BD.CLEARED_DATE) AS Mes_Conc, 
                      CR.CHECK_ID, CR.BANK_ACCOUNT_ID, MONTH(CR.POSTING_DATE) AS MES_POSTEO, YEAR(CR.POSTING_DATE) AS ANIO_POSTEO
FROM         dbo.CASH_RECEIPT AS CR INNER JOIN
                      dbo.CASH_RECEIPT_LINE AS CRL ON CR.CUSTOMER_ID = CRL.CUSTOMER_ID AND CR.CHECK_ID = CRL.CHECK_ID INNER JOIN
                      dbo.BANK_DEPOSIT AS BD ON CR.BANK_ACCOUNT_ID = BD.BANK_ACCOUNT_ID AND CR.DEPOSIT_ID = BD.DEPOSIT_ID INNER JOIN
                      dbo.CASH_RECEIPT_CURR AS CRC ON CR.CUSTOMER_ID = CRC.CUSTOMER_ID AND CR.CHECK_ID = CRC.CHECK_ID AND 
                      CR.CURRENCY_ID = CRC.CURRENCY_ID
WHERE     (CRL.GL_ACCOUNT_ID IS NULL)
GROUP BY CRL.CUSTOMER_ID, CRL.INVOICE_ID, CR.STATUS, CRC.SELL_RATE, CR.DEPOSIT_ID, CR.CURRENCY_ID, YEAR(BD.CLEARED_DATE), MONTH(BD.CLEARED_DATE),
                       CR.CHECK_ID, CR.BANK_ACCOUNT_ID, CR.POSTING_DATE, CR.SELL_RATE, CRL.SITE_ID
HAVING      (CR.STATUS <> 'X')
GO

-- VMX_IVA_CXC_02

IF EXISTS(SELECT * FROM sys.views WHERE name = 'VMX_IVA_CXC_02' AND schema_id = SCHEMA_ID('dbo'))
     DROP VIEW dbo.VMX_IVA_CXC_02
GO

CREATE VIEW [dbo].[VMX_IVA_CXC_02]
AS
SELECT     TOP (100) PERCENT VMX.SITE_ID, VMX.Cod_Cliente, VMX.Factura, VMX.Estatus, VMX.Monto_Deposito, VMX.BANK_ACCOUNT_ID, VMX.CHECK_ID, 
                      VMX.Cod_Deposito, VMX.TC_Deposito, VMX.Anio_Conc, VMX.Mes_Conc, R.TOTAL_AMOUNT, RL.VAT_AMOUNT, RL.VAT_GL_ACCT_ID, 
                      VMX.Monto_Deposito2 / R.TOTAL_AMOUNT * RL.VAT_AMOUNT AS MONTO_IVA_CURR, R.SELL_RATE AS TC_FACTURA, 
                      ROUND(VMX.Monto_Deposito2 / R.TOTAL_AMOUNT * RL.VAT_AMOUNT * R.SELL_RATE, 2, 0) AS IVA_MXN_TRASLADAR_FACT, 
                      ROUND(VMX.Monto_Deposito / R.TOTAL_AMOUNT * RL.VAT_AMOUNT * VMX.TC_Deposito, 2, 0) AS IVA_MXN_TRASLADAR_DEP, 
                      ROUND(VMX.Monto_Deposito / R.TOTAL_AMOUNT * RL.VAT_AMOUNT * VMX.TC_Deposito, 2, 0) 
                      - ROUND(VMX.Monto_Deposito2 / R.TOTAL_AMOUNT * RL.VAT_AMOUNT * R.SELL_RATE, 2, 0) AS PERDIDA_GANANCIA, VMX.MES_POSTEO, VMX.ANIO_POSTEO, 
                      CASE WHEN ROUND(VMX.Monto_Deposito / R.TOTAL_AMOUNT * RL.VAT_AMOUNT * VMX.TC_Deposito, 2, 0) 
                      - ROUND(VMX.Monto_Deposito2 / R.TOTAL_AMOUNT * RL.VAT_AMOUNT * R.SELL_RATE, 2, 0) < 0 THEN
                          (SELECT     GL_ACCOUNT_ID
                            FROM          GL_INTERFACE_ACCT
                            WHERE      (INTERFACE_ID = 'REALIZED_LOSS') AND (SITE_ID = R.SITE_ID)) ELSE
                          (SELECT     GL_ACCOUNT_ID
                            FROM          GL_INTERFACE_ACCT
                            WHERE      (INTERFACE_ID = 'REALIZED_GAIN') AND (SITE_ID = R.SITE_ID)) END AS CUENTA_PER_GANANCIA
FROM         dbo.RECEIVABLE AS R INNER JOIN
                      dbo.RECEIVABLE_LINE AS RL ON R.INVOICE_ID = RL.INVOICE_ID INNER JOIN
                      dbo.VMX_IVA_CXC_01 AS VMX ON R.INVOICE_ID = VMX.Factura AND R.SITE_ID = VMX.SITE_ID
ORDER BY VMX.CHECK_ID
GO

