-- VKTECH_D_ELIMINAR_POLIZA

IF OBJECT_ID('VKTECH_D_ELIMINAR_POLIZA', 'TR') IS NOT NULL 
   DROP TRIGGER VKTECH_D_ELIMINAR_POLIZA;
GO
CREATE TRIGGER VKTECH_D_ELIMINAR_POLIZA ON GJ AFTER DELETE
/*
Trigger que se ejecuta al eliminar una póliza de GJ
tambien se eliminara de la tabla VMXCONTROLPOLIZA Y VMX_CONTOLPOLIZA_LINE.
*/
AS
	DECLARE @TRANSACCION VARCHAR(15)
	DECLARE @SITE_ID VARCHAR(15)     
    
	SELECT @TRANSACCION = ID, @SITE_ID = SITE_ID FROM Deleted
	
	DELETE FROM VMX_CONTOLPOLIZA_LINE WHERE NO_TRANSACCION = @TRANSACCION AND SITE_ID = @SITE_ID
	DELETE FROM VMXCONTROLPOLIZA WHERE NO_TRANSACCION = @TRANSACCION AND SITE_ID = @SITE_ID
GO