--	[VMX_CUENTAS_RETENCION]

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VMX_CUENTAS_RETENCION]') AND type in (N'U'))
	IF(SELECT COUNT(CUENTA) FROM VMX_CUENTAS_RETENCION)> 0	
		PRINT 'La tabla [VMX_CUENTAS_RETENCION] contiene registros. Por motivos de seguridad no se puede eliminar. '
	ELSE		
		DROP TABLE VMX_CUENTAS_RETENCION	
GO
IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VMX_CUENTAS_RETENCION]') AND type in (N'U'))
CREATE TABLE [dbo].[VMX_CUENTAS_RETENCION](
	[Estado] [nchar](10) NOT NULL,
	[Cuenta] [nvarchar](30) NOT NULL,
	[Descripcion] [nvarchar](120) NOT NULL,
	[Retencion] [numeric](18, 2) NOT NULL,
	[Traslado] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_VMX_CUENTAS_RETENCION] PRIMARY KEY CLUSTERED 
(
	[Cuenta] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

GRANT SELECT, UPDATE, INSERT, DELETE ON [dbo].[VMX_CUENTAS_RETENCION] TO PUBLIC
GO

-- [VMX_CONTOLPOLIZA_LINE]
IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'VMX_CONTOLPOLIZA_LINE' AND COLUMN_NAME = 'MONTO_RET')
	ALTER TABLE dbo.VMX_CONTOLPOLIZA_LINE ADD MONTO_RET numeric(18, 3) NULL
GO
IF NOT EXISTS (SELECT OBJECT_NAME(OBJECT_ID) AS NameofConstraint,SCHEMA_NAME(schema_id) AS SchemaName,OBJECT_NAME(parent_object_id) AS TableName,type_desc AS ConstraintType FROM sys.objects WHERE type_desc LIKE '%CONSTRAINT' AND OBJECT_NAME(parent_object_id) = 'VMX_CONTOLPOLIZA_LINE' AND OBJECT_NAME(OBJECT_ID)='DF_VMX_CONTOLPOLIZA_LINE_MONTO_RET')
BEGIN
	ALTER TABLE dbo.VMX_CONTOLPOLIZA_LINE ADD CONSTRAINT
	DF_VMX_CONTOLPOLIZA_LINE_MONTO_RET DEFAULT 0 FOR MONTO_RET
END
GO
IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'VMX_CONTOLPOLIZA_LINE' AND COLUMN_NAME = 'RET_DEPOSITO')
	ALTER TABLE dbo.VMX_CONTOLPOLIZA_LINE ADD RET_DEPOSITO numeric(18, 3) NULL
GO
IF NOT EXISTS (SELECT OBJECT_NAME(OBJECT_ID) AS NameofConstraint,SCHEMA_NAME(schema_id) AS SchemaName,OBJECT_NAME(parent_object_id) AS TableName,type_desc AS ConstraintType FROM sys.objects WHERE type_desc LIKE '%CONSTRAINT' AND OBJECT_NAME(parent_object_id) = 'VMX_CONTOLPOLIZA_LINE' AND OBJECT_NAME(OBJECT_ID)='DF_VMX_CONTOLPOLIZA_LINE_RET_DEPOSITO')
BEGIN
	ALTER TABLE dbo.VMX_CONTOLPOLIZA_LINE ADD CONSTRAINT
	DF_VMX_CONTOLPOLIZA_LINE_RET_DEPOSITO DEFAULT 0 FOR RET_DEPOSITO
END
GO
	ALTER TABLE dbo.VMX_CONTOLPOLIZA_LINE SET (LOCK_ESCALATION = TABLE)
GO

-- [VMX_IVA_TRASL_CXP_01]

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VMX_IVA_TRASL_CXP_01]'))
DROP VIEW [dbo].[VMX_IVA_TRASL_CXP_01]
GO
CREATE VIEW [dbo].[VMX_IVA_TRASL_CXP_01]
AS
SELECT     CDL.SITE_ID, CDL.BANK_ACCOUNT_ID, CDL.CONTROL_NO, CD.VENDOR_ID, CD.CHECK_NO, CDL.PCURR_AMOUNT AS Monto_Pago, CDL.AMOUNT AS Monto_Pago2, 
                      CDC.SELL_RATE AS TC_Pago, CDL.SELL_RATE AS TC_Pago2, CD.CURRENCY_ID, CDL.VOUCHER_ID, CD.CLEARED, YEAR(CD.CLEARED_DATE) 
                      AS ANIO_CONCILIACION, MONTH(CD.CLEARED_DATE) AS MES_CONCILIACION, YEAR(CD.POSTING_DATE) AS ANIO_POSTEO, MONTH(CD.POSTING_DATE) 
                      AS MES_POSTEO
FROM         dbo.CASH_DISBURSE_LINE AS CDL INNER JOIN
                      dbo.CASH_DISBURSEMENT AS CD ON CDL.BANK_ACCOUNT_ID = CD.BANK_ACCOUNT_ID AND CDL.CONTROL_NO = CD.CONTROL_NO INNER JOIN
                      dbo.CASH_DISBURSE_CURR AS CDC ON CD.BANK_ACCOUNT_ID = CDC.BANK_ACCOUNT_ID AND CD.CONTROL_NO = CDC.CONTROL_NO AND 
                      CD.CURRENCY_ID = CDC.CURRENCY_ID
WHERE     (CDL.VOUCHER_ID IS NOT NULL) AND (CD.STATUS <> 'X')


GO

GRANT SELECT ON dbo.VMX_IVA_TRASL_CXP_01 TO PUBLIC
GO

-- [VMX_IVA_TRASL_CXP_02]
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VMX_IVA_TRASL_CXP_02]'))
DROP VIEW [dbo].[VMX_IVA_TRASL_CXP_02]
GO
CREATE VIEW [dbo].[VMX_IVA_TRASL_CXP_02]
AS
SELECT     VMX.SITE_ID, VMX.BANK_ACCOUNT_ID, VMX.CONTROL_NO, VMX.VENDOR_ID, VMX.CHECK_NO, VMX.Monto_Pago, VMX.TC_Pago, VMX.CURRENCY_ID, 
                      VMX.VOUCHER_ID, P.INVOICE_ID, VMX.CLEARED, VMX.ANIO_CONCILIACION, VMX.MES_CONCILIACION, PL.LINE_NO, PL.VAT_AMOUNT, PL.VAT_GL_ACCT_ID, 
                      P.TOTAL_AMOUNT, PL.AMOUNT, P.SELL_RATE AS TC_FACTURA, CASE WHEN P.TOTAL_AMOUNT = 0 THEN 0 ELSE ROUND(VMX.TC_PAGO / P.TOTAL_AMOUNT, 3, 0) 
                      END AS PORC_PAGO, CASE WHEN P.TOTAL_AMOUNT = 0 THEN 0 ELSE ROUND(VMX.TC_PAGO / P.TOTAL_AMOUNT * PL.VAT_AMOUNT, 3, 0) 
                      END AS IVA_TRASLADO_NATIVO, ROUND(VMX.Monto_Pago2 / P.TOTAL_AMOUNT * PL.VAT_AMOUNT * P.SELL_RATE, 2, 0) AS IVA_TRASLADO_MXN_FACT, 
                      ROUND(VMX.Monto_Pago / P.TOTAL_AMOUNT * PL.VAT_AMOUNT * VMX.TC_Pago, 2, 0) AS IVA_TRASLADO_MXN_PAGO, 
                      ROUND(VMX.Monto_Pago2 / P.TOTAL_AMOUNT * PL.VAT_AMOUNT * P.SELL_RATE, 2, 0) 
                      - ROUND(VMX.Monto_Pago / P.TOTAL_AMOUNT * PL.VAT_AMOUNT * VMX.TC_Pago, 2, 0) AS GANANCIA_PERDIDA, 
                      CASE WHEN ROUND(VMX.Monto_Pago2 / P.TOTAL_AMOUNT * PL.VAT_AMOUNT * P.SELL_RATE, 2, 0) 
                      - ROUND(VMX.Monto_Pago / P.TOTAL_AMOUNT * PL.VAT_AMOUNT * VMX.TC_Pago, 2, 0) < 0 THEN
                          (SELECT     GL_ACCOUNT_ID
                            FROM          GL_INTERFACE_ACCT
                            WHERE      (INTERFACE_ID = 'REALIZED_LOSS') AND (SITE_ID = P.SITE_ID)) ELSE
                          (SELECT     GL_ACCOUNT_ID
                            FROM          GL_INTERFACE_ACCT
                            WHERE      (INTERFACE_ID = 'REALIZED_GAIN') AND (SITE_ID = P.SITE_ID)) END AS CUENTA_PER_GANANCIA, VMX.ANIO_POSTEO, VMX.MES_POSTEO
FROM         dbo.VMX_IVA_TRASL_CXP_01 AS VMX INNER JOIN
                      dbo.PAYABLE AS P ON VMX.VOUCHER_ID = P.VOUCHER_ID AND VMX.SITE_ID = P.SITE_ID INNER JOIN
                      dbo.PAYABLE_LINE AS PL ON P.VOUCHER_ID = PL.VOUCHER_ID

GO


GRANT SELECT ON dbo.VMX_IVA_TRASL_CXP_02 TO PUBLIC
GO

-- [VMX_IVA_TRASL_CXP_03]

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VMX_IVA_TRASL_CXP_03]'))
DROP VIEW [dbo].[VMX_IVA_TRASL_CXP_03]
GO
CREATE VIEW [dbo].[VMX_IVA_TRASL_CXP_03]
AS
SELECT     VMX.SITE_ID, VMX.BANK_ACCOUNT_ID, VMX.CONTROL_NO, VMX.VENDOR_ID, VMX.CHECK_NO, VMX.Monto_Pago, VMX.TC_Pago, VMX.CURRENCY_ID, 
                      VMX.VOUCHER_ID, P.INVOICE_ID, VMX.CLEARED, VMX.ANIO_CONCILIACION, VMX.MES_CONCILIACION, PL.LINE_NO, - PL.AMOUNT AS AMOUNT, 
                      PL.GL_ACCOUNT_ID, P.TOTAL_AMOUNT, P.SELL_RATE AS TC_FACTURA, CASE WHEN P.TOTAL_AMOUNT = 0 THEN 0 ELSE (- 1) 
                      * ROUND(VMX.TC_PAGO / P.TOTAL_AMOUNT, 3, 0) END AS PORC_PAGO, CASE WHEN P.TOTAL_AMOUNT = 0 THEN 0 ELSE (- 1) 
                      * ROUND((VMX.TC_PAGO / P.TOTAL_AMOUNT) * PL.AMOUNT, 3, 0) END AS RET_TRASLADO_NATIVO, ROUND((VMX.Monto_Pago2 / P.TOTAL_AMOUNT) 
                      * (PL.AMOUNT * - 1) * P.SELL_RATE, 2, 0) AS RETENCION_MXN_FACT, ROUND((VMX.Monto_Pago / P.TOTAL_AMOUNT) * (PL.AMOUNT * - 1) * VMX.TC_Pago, 2, 0) 
                      AS RETENCION_MXN_PAGO, ROUND((VMX.Monto_Pago2 / P.TOTAL_AMOUNT) * (PL.AMOUNT * - 1) * P.SELL_RATE, 2, 0) 
                      - ROUND((VMX.Monto_Pago / P.TOTAL_AMOUNT) * (PL.AMOUNT * - 1) * VMX.TC_Pago, 2, 0) AS GANANCIA_PERDIDA, 
                      CASE WHEN ROUND(VMX.Monto_Pago2 / P.TOTAL_AMOUNT * (PL.AMOUNT * - 1) * P.SELL_RATE, 2, 0) 
                      - ROUND(VMX.Monto_Pago / P.TOTAL_AMOUNT * (PL.AMOUNT * - 1) * VMX.TC_Pago, 2, 0) < 0 THEN
                          (SELECT     GL_ACCOUNT_ID
                            FROM          GL_INTERFACE_ACCT
                            WHERE      (INTERFACE_ID = 'REALIZED_LOSS') AND (SITE_ID = P.SITE_ID)) ELSE
                          (SELECT     GL_ACCOUNT_ID
                            FROM          GL_INTERFACE_ACCT
                            WHERE      (INTERFACE_ID = 'REALIZED_GAIN') AND (SITE_ID = P.SITE_ID)) END AS CUENTA_PER_GANANCIA, VMX.ANIO_POSTEO, VMX.MES_POSTEO, 
                      PL.AMOUNT AS Expr1
FROM         dbo.VMX_IVA_TRASL_CXP_01 AS VMX INNER JOIN
                      dbo.PAYABLE AS P ON VMX.VOUCHER_ID = P.VOUCHER_ID AND VMX.SITE_ID = P.SITE_ID INNER JOIN
                      dbo.PAYABLE_LINE AS PL ON P.VOUCHER_ID = PL.VOUCHER_ID INNER JOIN
                      dbo.VMX_CUENTAS_RETENCION AS VCR ON PL.GL_ACCOUNT_ID = VCR.Cuenta
WHERE     (VCR.Estado = N'True')

GO

GRANT SELECT ON dbo.VMX_IVA_TRASL_CXP_03 TO PUBLIC
GO

-- [VMX_IVA_CXC_01]

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VMX_IVA_CXC_01]'))
DROP VIEW [dbo].[VMX_IVA_CXC_01]
GO
CREATE VIEW [dbo].[VMX_IVA_CXC_01]
AS
SELECT     CRL.SITE_ID, CRL.CUSTOMER_ID AS Cod_Cliente, CRL.INVOICE_ID AS Factura, SUM(CRL.PCURR_AMOUNT) AS Monto_Deposito, SUM(CRL.AMOUNT) 
                      AS Monto_Deposito2, CR.STATUS AS Estatus,
                          (SELECT     CURRENCY_ID
                            FROM          dbo.RECEIVABLE
                            WHERE      (INVOICE_ID = CRL.INVOICE_ID)) AS Expr1, CR.CURRENCY_ID, CRC.SELL_RATE AS TC_Deposito, CR.SELL_RATE AS TC_Deposito2, 
                      CR.DEPOSIT_ID AS Cod_Deposito, CR.CURRENCY_ID AS Moneda_Deposito, YEAR(BD.CLEARED_DATE) AS Anio_Conc, MONTH(BD.CLEARED_DATE) AS Mes_Conc, 
                      CR.CHECK_ID, CR.BANK_ACCOUNT_ID, MONTH(CR.POSTING_DATE) AS MES_POSTEO, YEAR(CR.POSTING_DATE) AS ANIO_POSTEO
FROM         dbo.CASH_RECEIPT AS CR INNER JOIN
                      dbo.CASH_RECEIPT_LINE AS CRL ON CR.CUSTOMER_ID = CRL.CUSTOMER_ID AND CR.CHECK_ID = CRL.CHECK_ID INNER JOIN
                      dbo.BANK_DEPOSIT AS BD ON CR.BANK_ACCOUNT_ID = BD.BANK_ACCOUNT_ID AND CR.DEPOSIT_ID = BD.DEPOSIT_ID INNER JOIN
                      dbo.CASH_RECEIPT_CURR AS CRC ON CR.CUSTOMER_ID = CRC.CUSTOMER_ID AND CR.CHECK_ID = CRC.CHECK_ID AND 
                      CR.CURRENCY_ID = CRC.CURRENCY_ID
WHERE     (CRL.GL_ACCOUNT_ID IS NULL)
GROUP BY CRL.CUSTOMER_ID, CRL.INVOICE_ID, CR.STATUS, CRC.SELL_RATE, CR.DEPOSIT_ID, CR.CURRENCY_ID, YEAR(BD.CLEARED_DATE), MONTH(BD.CLEARED_DATE),
                       CR.CHECK_ID, CR.BANK_ACCOUNT_ID, CR.POSTING_DATE, CR.SELL_RATE, CRL.SITE_ID
HAVING      (CR.STATUS <> 'X')


GO

GRANT SELECT ON dbo.[VMX_IVA_CXC_01] TO PUBLIC
GO

-- [VMX_IVA_CXC_02]

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VMX_IVA_CXC_02]'))
DROP VIEW [dbo].[VMX_IVA_CXC_02]
GO
CREATE VIEW [dbo].[VMX_IVA_CXC_02]
AS
SELECT     TOP (100) PERCENT VMX.SITE_ID, VMX.Cod_Cliente, VMX.Factura, VMX.Estatus, VMX.Monto_Deposito, VMX.BANK_ACCOUNT_ID, VMX.CHECK_ID, VMX.Cod_Deposito, VMX.TC_Deposito, 
                      VMX.Anio_Conc, VMX.Mes_Conc, R.TOTAL_AMOUNT, RL.LINE_NO, RL.AMOUNT, RL.VAT_AMOUNT, RL.VAT_GL_ACCT_ID, 
                      VMX.Monto_Deposito2 / R.TOTAL_AMOUNT * RL.VAT_AMOUNT AS MONTO_IVA_CURR, R.SELL_RATE AS TC_FACTURA, 
                      ROUND(VMX.Monto_Deposito2 / R.TOTAL_AMOUNT * RL.VAT_AMOUNT * R.SELL_RATE, 2, 0) AS IVA_MXN_TRASLADAR_FACT, 
                      ROUND(VMX.Monto_Deposito / R.TOTAL_AMOUNT * RL.VAT_AMOUNT * VMX.TC_Deposito, 2, 0) AS IVA_MXN_TRASLADAR_DEP, 
                      ROUND(VMX.Monto_Deposito / R.TOTAL_AMOUNT * RL.VAT_AMOUNT * VMX.TC_Deposito, 2, 0) - ROUND(VMX.Monto_Deposito2 / R.TOTAL_AMOUNT * RL.VAT_AMOUNT * R.SELL_RATE, 2, 0) 
                      AS PERDIDA_GANANCIA, VMX.MES_POSTEO, VMX.ANIO_POSTEO, CASE WHEN ROUND(VMX.Monto_Deposito / R.TOTAL_AMOUNT * RL.VAT_AMOUNT * VMX.TC_Deposito, 2, 0) 
                      - ROUND(VMX.Monto_Deposito2 / R.TOTAL_AMOUNT * RL.VAT_AMOUNT * R.SELL_RATE, 2, 0) < 0 THEN
                          (SELECT     GL_ACCOUNT_ID
                            FROM          GL_INTERFACE_ACCT
                            WHERE      (INTERFACE_ID = 'REALIZED_LOSS') AND (SITE_ID = R.SITE_ID)) ELSE
                          (SELECT     GL_ACCOUNT_ID
                            FROM          GL_INTERFACE_ACCT
                            WHERE      (INTERFACE_ID = 'REALIZED_GAIN') AND (SITE_ID = R.SITE_ID)) END AS CUENTA_PER_GANANCIA
FROM         dbo.RECEIVABLE AS R INNER JOIN
                      dbo.RECEIVABLE_LINE AS RL ON R.INVOICE_ID = RL.INVOICE_ID INNER JOIN
                      dbo.VMX_IVA_CXC_01 AS VMX ON R.INVOICE_ID = VMX.Factura AND R.SITE_ID = VMX.SITE_ID
ORDER BY VMX.CHECK_ID

GO
GRANT SELECT ON dbo.[VMX_IVA_CXC_02] TO PUBLIC
GO

--	[PRC_POLIZAS_POR_TRASPASAR_CXC]

IF OBJECT_ID ( 'PRC_POLIZAS_POR_TRASPASAR_CXC', 'P' ) IS NOT NULL 
    DROP PROCEDURE dbo.PRC_POLIZAS_POR_TRASPASAR_CXC;
GO
CREATE PROCEDURE [dbo].[PRC_POLIZAS_POR_TRASPASAR_CXC] (@ANIO INT,@MES INT, @FECHA VARCHAR(15),@CONSILIADO INT, @SITE_ID VARCHAR(15))
AS
	SET NOCOUNT ON;
  
    CREATE TABLE #POLIZASCXC(	 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO VARCHAR(15),
    VAT_GL_ACCT_ID VARCHAR(30),
    DESCRIPCION VARCHAR(200),
    TRASLADO VARCHAR(30),
    TC_FACTURA DECIMAL(15,8),
    TC_DEPOSITO DECIMAL(15,8),    
    IVA_MXN_TRASLADAR_FACT DECIMAL(15,2),
    IVA_MXN_TRASLADAR_DEP DECIMAL(15,2),
    PERDIDA_GANANCIA DECIMAL(15,2),
    CUENTA_PER_GANANCIA VARCHAR(30),
    FECHA VARCHAR(10),
    CLIENTE VARCHAR(120),
    SITE_ID VARCHAR(15));
    
	CREATE TABLE #POLIZASNEGATIVAS( 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO VARCHAR(15),
    SITE_ID VARCHAR(15));
	
	IF (@CONSILIADO = 1)
	BEGIN
		-- Obtener todos los movimientos consiliados
		INSERT #POLIZASCXC(SITE_ID,BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, IVA_MXN_TRASLADAR_FACT, TC_DEPOSITO, IVA_MXN_TRASLADAR_DEP, PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE)
			SELECT C.SITE_ID, C.BANK_ACCOUNT_ID
				,C.CHECK_ID
                ,C.VAT_GL_ACCT_ID
                ,CTA.DESCRIPCION
                ,CTA.TRASLADO
                ,TC_FACTURA
                -- Hacer cero el monto, cuando el Monto de IVA prorrateado sea un centavo positivo o negativo.
                ,CASE 
					WHEN SUM(C.IVA_MXN_TRASLADAR_FACT) = 0.01 THEN 0 
					WHEN SUM(C.IVA_MXN_TRASLADAR_FACT) = -0.01 THEN 0 
				ELSE SUM(C.IVA_MXN_TRASLADAR_FACT)END                             
				,TC_DEPOSITO				
				,CASE 
					WHEN SUM(PERDIDA_GANANCIA) = 0.01 THEN IVA_MXN_TRASLADAR_DEP - 0.01
					WHEN SUM(PERDIDA_GANANCIA) = -0.01 THEN IVA_MXN_TRASLADAR_DEP + 0.01
				ELSE SUM(IVA_MXN_TRASLADAR_DEP) END AS IVA_MXN_TRASLADAR_DEP							
				,CASE 
					WHEN SUM(PERDIDA_GANANCIA) = 0.01 THEN 0 
					WHEN SUM(PERDIDA_GANANCIA) = -0.01 THEN 0 
				ELSE SUM(PERDIDA_GANANCIA)END									
				,CUENTA_PER_GANANCIA			
				,@FECHA
				,C.COD_CLIENTE
			FROM ACCOUNT AS A, VMX_IVA_CXC_02 AS C, VMX_IVACUENTASCXC AS CTA
			WHERE CTA.Traslado = A.ID
				AND CTA.Cuenta = C.VAT_GL_ACCT_ID
				AND CTA.Estado = 'True'
				AND C.Anio_Conc = @ANIO
				AND C.Mes_conc = @MES
				AND C.SITE_ID = @SITE_ID
            GROUP BY C.SITE_ID, C.BANK_ACCOUNT_ID,C.CHECK_ID,C.VAT_GL_ACCT_ID,CTA.Descripcion
				,C.TC_FACTURA,CTA.Traslado,A.DESCRIPTION,C.Cod_Cliente,TC_DEPOSITO
				,IVA_MXN_TRASLADAR_DEP
				,PERDIDA_GANANCIA
				,CUENTA_PER_GANANCIA
			
			-- Obtener los movimientos con montos negativos
			INSERT #POLIZASNEGATIVAS(SITE_ID, BANK_ACCOUNT_ID,CONTROL_NO)
			SELECT CXC.SITE_ID, CXC.BANK_ACCOUNT_ID,CXC.CHECK_ID
			FROM ACCOUNT AS AC, VMX_IVA_CXC_02 AS CXC, VMX_IVACUENTASCXC AS CTAS
			WHERE CTAS.Traslado = AC.ID
				AND CTAS.Cuenta = CXC.VAT_GL_ACCT_ID
				AND CTAS.Estado = 'True'
				AND CXC.Anio_Conc = @ANIO
				AND CXC.Mes_conc = @MES
				AND CXC.SITE_ID = @SITE_ID
			GROUP BY CXC.SITE_ID, CXC.BANK_ACCOUNT_ID,CXC.CHECK_ID,CXC.VAT_GL_ACCT_ID        
			HAVING CASE WHEN SUM(CXC.IVA_MXN_TRASLADAR_FACT) = 0.01 THEN 0 WHEN SUM(CXC.IVA_MXN_TRASLADAR_FACT) = -0.01 THEN 0 ELSE SUM(CXC.IVA_MXN_TRASLADAR_FACT) END < 0
	END
	ELSE
	BEGIN
		-- Obtener todos los movimientos consiliados y no consiliados
		INSERT #POLIZASCXC(SITE_ID, BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, IVA_MXN_TRASLADAR_FACT, TC_DEPOSITO, IVA_MXN_TRASLADAR_DEP, PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE)
			SELECT C.SITE_ID 
				,C.BANK_ACCOUNT_ID
				,C.CHECK_ID
                ,C.VAT_GL_ACCT_ID
                ,CTA.DESCRIPCION
                ,CTA.TRASLADO
                ,TC_FACTURA
                -- Hacer cero el monto, cuando el Monto de IVA prorrateado sea un centavo positivo o negativo.
                ,CASE WHEN SUM(C.IVA_MXN_TRASLADAR_FACT) = 0.01 THEN 0 
					WHEN SUM(C.IVA_MXN_TRASLADAR_FACT) = -0.01 THEN 0 ELSE SUM(C.IVA_MXN_TRASLADAR_FACT)END                             
				,TC_DEPOSITO				
				,CASE 
					WHEN SUM(PERDIDA_GANANCIA) = 0.01 THEN IVA_MXN_TRASLADAR_DEP - 0.01
					WHEN SUM(PERDIDA_GANANCIA) = -0.01 THEN IVA_MXN_TRASLADAR_DEP + 0.01
				ELSE IVA_MXN_TRASLADAR_DEP END AS IVA_MXN_TRASLADAR_DEP							
				,CASE WHEN SUM(PERDIDA_GANANCIA) = 0.01 THEN 0 
					WHEN SUM(PERDIDA_GANANCIA) = -0.01 THEN 0 ELSE SUM(PERDIDA_GANANCIA)END									
				,CUENTA_PER_GANANCIA
				,@FECHA
				,C.COD_CLIENTE
			FROM ACCOUNT AS A, VMX_IVA_CXC_02 AS C, VMX_IVACUENTASCXC AS CTA
			WHERE CTA.Traslado = A.ID
				AND CTA.Cuenta = C.VAT_GL_ACCT_ID
				AND CTA.Estado = 'True'
				AND C.ANIO_POSTEO = @ANIO
				AND C.MES_POSTEO = @MES
				AND C.SITE_ID = @SITE_ID
            GROUP BY C.SITE_ID, C.BANK_ACCOUNT_ID,C.CHECK_ID,C.VAT_GL_ACCT_ID,CTA.Descripcion
				,C.TC_FACTURA,CTA.Traslado,A.DESCRIPTION,C.Cod_Cliente,TC_DEPOSITO
				,IVA_MXN_TRASLADAR_DEP
				,PERDIDA_GANANCIA
				,CUENTA_PER_GANANCIA
		
		-- Obtener los movimientos con montos negativos
		INSERT #POLIZASNEGATIVAS(SITE_ID, BANK_ACCOUNT_ID,CONTROL_NO)
			SELECT CXC.SITE_ID, CXC.BANK_ACCOUNT_ID,CXC.CHECK_ID
			FROM ACCOUNT AS AC, VMX_IVA_CXC_02 AS CXC, VMX_IVACUENTASCXC AS CTAS
			WHERE CTAS.Traslado = AC.ID
				AND CTAS.Cuenta = CXC.VAT_GL_ACCT_ID
				AND CTAS.Estado = 'True'
				AND CXC.ANIO_POSTEO = @ANIO
				AND CXC.MES_POSTEO = @MES
				AND CXC.SITE_ID = @SITE_ID
			GROUP BY CXC.SITE_ID, CXC.BANK_ACCOUNT_ID,CXC.CHECK_ID,CXC.VAT_GL_ACCT_ID    
			HAVING CASE WHEN SUM(CXC.IVA_MXN_TRASLADAR_FACT) = 0.01 THEN 0 WHEN SUM(CXC.IVA_MXN_TRASLADAR_FACT) = -0.01 THEN 0 ELSE SUM(CXC.IVA_MXN_TRASLADAR_FACT) END < 0
	END		
    
    -- Eliminar las polizas negativas. Filtrar por Banco y No. Control                        
	DELETE FROM #POLIZASCXC
	FROM #POLIZASCXC AS P LEFT JOIN #POLIZASNEGATIVAS AS N ON P.BANK_ACCOUNT_ID = N.BANK_ACCOUNT_ID AND P.CONTROL_NO = N.CONTROL_NO AND P.SITE_ID = N.SITE_ID
	WHERE N.BANK_ACCOUNT_ID IS NOT NULL AND N.CONTROL_NO IS NOT NULL
	
	-- Eliminar las polizas que han completado el traspaso de IVA.
	DELETE FROM #POLIZASCXC
	FROM #POLIZASCXC AS P 
		LEFT JOIN VMX_CONTOLPOLIZA_LINE AS PL 
			ON P.BANK_ACCOUNT_ID = PL.BANK_ACCOUNT_ID AND P.CONTROL_NO = PL.CHECK_ID AND P.SITE_ID = PL.SITE_ID AND PL.CUSTOMER_ID = P.CLIENTE --AND P.VAT_GL_ACCT_ID = PL.CUENTA
	WHERE PL.BANK_ACCOUNT_ID IS NOT NULL AND PL.CHECK_ID IS NOT NULL AND PL.CUENTA IS NOT NULL
		AND PL.TIPO_OPERACION = 'CXC'
		   
	SELECT SITE_ID
		,BANK_ACCOUNT_ID
		,CONTROL_NO
		,CLIENTE
		,VAT_GL_ACCT_ID
		,DESCRIPCION
		,TRASLADO
		,TC_FACTURA
		,TC_DEPOSITO
		,ISNULL(IVA_MXN_TRASLADAR_FACT,0.0) AS IVA_MXN_TRASLADAR_FACT
		,ISNULL(IVA_MXN_TRASLADAR_DEP,0.0) AS IVA_MXN_TRASLADAR_DEP
		,0.00 AS RET_MXN_TRASLADAR_FACT
		,0.00 AS RET_MXN_TRASLADAR_DEP
		,ISNULL(PERDIDA_GANANCIA,0.0) AS PERDIDA_GANANCIA
		,CUENTA_PER_GANANCIA
		,FECHA
	FROM #POLIZASCXC
	ORDER BY BANK_ACCOUNT_ID,CONTROL_NO

	DROP TABLE #POLIZASCXC
	DROP TABLE #POLIZASNEGATIVAS

GO

GRANT EXECUTE ON dbo.[PRC_POLIZAS_POR_TRASPASAR_CXC] TO PUBLIC
GO

--	[PRC_POLIZAS_POR_TRASPASAR_CXP]

IF OBJECT_ID ( 'PRC_POLIZAS_POR_TRASPASAR_CXP', 'P' ) IS NOT NULL 
    DROP PROCEDURE dbo.PRC_POLIZAS_POR_TRASPASAR_CXP;
GO
CREATE PROCEDURE [dbo].[PRC_POLIZAS_POR_TRASPASAR_CXP] (@ANIO INT,@MES INT, @FECHA VARCHAR(15),@CONSILIADO INT, @SITE_ID VARCHAR(15))
AS
	SET NOCOUNT ON;

    CREATE TABLE #POLIZASCXP(	 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO INT,
    VAT_GL_ACCT_ID VARCHAR(30),
    DESCRIPCION VARCHAR(200),
    TRASLADO VARCHAR(30),
    TC_FACTURA DECIMAL(15,8),
    TC_DEPOSITO DECIMAL(15,8),    
    IVA_MXN_TRASLADAR_FACT DECIMAL(15,2),
    IVA_MXN_TRASLADAR_DEP DECIMAL(15,2),
    PERDIDA_GANANCIA DECIMAL(15,2),
    CUENTA_PER_GANANCIA VARCHAR(30),
    FECHA VARCHAR(10),
    CLIENTE VARCHAR(120),
    SITE_ID VARCHAR(15));

	CREATE TABLE #POLIZASNEGATIVAS( 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO INT,
    SITE_ID VARCHAR(15));
	
	IF (@CONSILIADO = 1)
	BEGIN
		-- Obtener todos los movimientos consiliados		
		INSERT #POLIZASCXP(SITE_ID, BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, IVA_MXN_TRASLADAR_FACT, TC_DEPOSITO, IVA_MXN_TRASLADAR_DEP, PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE)
			SELECT A.SITE_ID
				, A.BANK_ACCOUNT_ID 
				,A.CONTROL_NO 
				,A.VAT_GL_ACCT_ID
				,B.DESCRIPCION
				,B.TRASLADO
				,A.TC_FACTURA
				-- Hacer cero el monto, cuando el Monto de IVA prorrateado sea un centavo positivo o negativo.
				,CASE 
					WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = 0.01 THEN 0 
					WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = -0.01 THEN 0 
				ELSE SUM(A.IVA_TRASLADO_MXN_FACT)  END
				,A.TC_Pago				
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN A.IVA_TRASLADO_MXN_PAGO + 0.01
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN A.IVA_TRASLADO_MXN_PAGO - 0.01
				ELSE SUM(A.IVA_TRASLADO_MXN_PAGO) END AS IVA_MXN_TRASLADAR_DEP	
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN 0 
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN 0 
				ELSE SUM(A.GANANCIA_PERDIDA)END
				,A.CUENTA_PER_GANANCIA
				,@FECHA
				,A.VENDOR_ID
			FROM VMX_IVA_TRASL_CXP_02 AS a,VMX_DIOTCUENTAS AS b 
			WHERE b.Cuenta =  a.VAT_GL_ACCT_ID
				AND b.Estado = 'True'
				AND a.ANIO_CONCILIACION = @ANIO
				AND a.MES_CONCILIACION = @MES	
				AND a.SITE_ID = @SITE_ID			
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO,a.VAT_GL_ACCT_ID,b.Descripcion,a.TC_FACTURA,b.Traslado,A.IVA_TRASLADO_MXN_FACT,
				A.TC_Pago,A.IVA_TRASLADO_MXN_PAGO,A.GANANCIA_PERDIDA,A.CUENTA_PER_GANANCIA,a.VENDOR_ID
			
			-- Obtener los movimientos con montos negativos
			INSERT #POLIZASNEGATIVAS(SITE_ID,BANK_ACCOUNT_ID,CONTROL_NO)
				SELECT A.SITE_ID, A.BANK_ACCOUNT_ID,A.CONTROL_NO      
				FROM VMX_IVA_TRASL_CXP_02 AS a,VMX_DIOTCUENTAS AS b 
				WHERE b.Cuenta =  a.VAT_GL_ACCT_ID AND b.Estado = 'True' 
					-- Consiliados
					AND a.ANIO_CONCILIACION = @ANIO AND a.MES_CONCILIACION = @MES AND a.SITE_ID = @SITE_ID
				GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO	,a.VAT_GL_ACCT_ID        
				HAVING CASE WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = 0.01 THEN 0 WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = -0.01 THEN 0 ELSE SUM(A.IVA_TRASLADO_MXN_FACT)END < 0
	END
	ELSE
	BEGIN
		-- Obtener todos los movimientos consiliados y no consiliados
		INSERT #POLIZASCXP(SITE_ID, BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, IVA_MXN_TRASLADAR_FACT, TC_DEPOSITO, IVA_MXN_TRASLADAR_DEP, PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE)
			SELECT A.SITE_ID
				,A.BANK_ACCOUNT_ID 
				,A.CONTROL_NO 
				,A.VAT_GL_ACCT_ID
				,B.DESCRIPCION
				,B.TRASLADO
				,A.TC_FACTURA
				-- Hacer cero el monto, cuando el Monto de IVA prorrateado sea un centavo positivo o negativo.
				,CASE 
					WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = 0.01 THEN 0 
					WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = -0.01 THEN 0 
				ELSE SUM(A.IVA_TRASLADO_MXN_FACT)  END
				,A.TC_Pago				
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN A.IVA_TRASLADO_MXN_PAGO + 0.01
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN A.IVA_TRASLADO_MXN_PAGO - 0.01
				ELSE SUM(A.IVA_TRASLADO_MXN_PAGO) END AS IVA_MXN_TRASLADAR_DEP	
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN 0 
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN 0 
				ELSE SUM(A.GANANCIA_PERDIDA)END
				,A.CUENTA_PER_GANANCIA
				,@FECHA
				,A.VENDOR_ID
			FROM VMX_IVA_TRASL_CXP_02 AS a,VMX_DIOTCUENTAS AS b 
			WHERE b.Cuenta =  a.VAT_GL_ACCT_ID
				AND b.Estado = 'True'
				AND a.ANIO_POSTEO = @ANIO
				AND a.MES_POSTEO = @MES
				AND a.SITE_ID = @SITE_ID
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO,a.VAT_GL_ACCT_ID,b.Descripcion,a.TC_FACTURA,b.Traslado,A.IVA_TRASLADO_MXN_FACT,
				A.TC_Pago,A.IVA_TRASLADO_MXN_PAGO,A.GANANCIA_PERDIDA,A.CUENTA_PER_GANANCIA,a.VENDOR_ID
		
		-- Obtener los movimientos con montos negativos
		INSERT #POLIZASNEGATIVAS(SITE_ID, BANK_ACCOUNT_ID,CONTROL_NO)
			SELECT A.SITE_ID, A.BANK_ACCOUNT_ID,A.CONTROL_NO      
			FROM VMX_IVA_TRASL_CXP_02 AS a,VMX_DIOTCUENTAS AS b 
			WHERE b.Cuenta =  a.VAT_GL_ACCT_ID AND b.Estado = 'True' 
				-- No Consiliados
				AND a.ANIO_POSTEO = @ANIO AND a.MES_POSTEO = @MES AND a.SITE_ID = @SITE_ID
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO	,a.VAT_GL_ACCT_ID        
			HAVING CASE WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = 0.01 THEN 0 WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = -0.01 THEN 0 ELSE SUM(A.IVA_TRASLADO_MXN_FACT)END < 0
	END		
    
    -- Eliminar las polizas negativas. Filtrar por Banco y No. Control                        
	DELETE FROM #POLIZASCXP 
	FROM #POLIZASCXP AS P LEFT JOIN #POLIZASNEGATIVAS AS N ON P.BANK_ACCOUNT_ID = N.BANK_ACCOUNT_ID AND P.CONTROL_NO = N.CONTROL_NO AND P.SITE_ID = N.SITE_ID
	WHERE N.BANK_ACCOUNT_ID IS NOT NULL AND N.CONTROL_NO IS NOT NULL
	
	-- Eliminar las polizas que han completado el traspaso de IVA.
	DELETE FROM #POLIZASCXP
	FROM #POLIZASCXP AS P 
		LEFT JOIN VMX_CONTOLPOLIZA_LINE AS PL 
			ON P.BANK_ACCOUNT_ID = PL.BANK_ACCOUNT_ID AND P.CONTROL_NO = PL.CONTROL_NO AND P.VAT_GL_ACCT_ID = PL.CUENTA AND P.SITE_ID = PL.SITE_ID AND PL.CUSTOMER_ID = P.CLIENTE
	WHERE PL.BANK_ACCOUNT_ID IS NOT NULL AND PL.CONTROL_NO IS NOT NULL AND PL.CUENTA IS NOT NULL
		AND PL.TIPO_OPERACION = 'CXP'
	
	SELECT SITE_ID
		,BANK_ACCOUNT_ID
		,CONTROL_NO
		,CLIENTE
		,VAT_GL_ACCT_ID
		,DESCRIPCION
		,TRASLADO
		,TC_FACTURA
		,TC_DEPOSITO
		,ISNULL(IVA_MXN_TRASLADAR_FACT,0.0) AS IVA_MXN_TRASLADAR_FACT
		,ISNULL(IVA_MXN_TRASLADAR_DEP,0.0) AS IVA_MXN_TRASLADAR_DEP
		,0.00 RET_MXN_TRASLADAR_FACT
		,0.00 RET_MXN_TRASLADAR_DEP
		,ISNULL(PERDIDA_GANANCIA,0.0) AS PERDIDA_GANANCIA
		,CUENTA_PER_GANANCIA
		,FECHA
	FROM #POLIZASCXP
	ORDER BY BANK_ACCOUNT_ID,CONTROL_NO

	DROP TABLE #POLIZASCXP                    
	DROP TABLE #POLIZASNEGATIVAS

GO

GRANT EXECUTE ON dbo.[PRC_POLIZAS_POR_TRASPASAR_CXP] TO PUBLIC
GO

--	[PRC_POLIZAS_POR_TRASPASAR_RET_CXP]

IF OBJECT_ID ( 'PRC_POLIZAS_POR_TRASPASAR_RET_CXP', 'P' ) IS NOT NULL 
    DROP PROCEDURE dbo.PRC_POLIZAS_POR_TRASPASAR_RET_CXP;
GO
CREATE PROCEDURE [dbo].[PRC_POLIZAS_POR_TRASPASAR_RET_CXP] (@ANIO INT,@MES INT, @FECHA VARCHAR(15),@CONSILIADO INT, @SITE_ID VARCHAR(15))
AS
	SET NOCOUNT ON;

    CREATE TABLE #POLIZASCXP(	 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO INT,
    VAT_GL_ACCT_ID VARCHAR(30),
    DESCRIPCION VARCHAR(200),
    TRASLADO VARCHAR(30),
    TC_FACTURA DECIMAL(15,8),
    TC_DEPOSITO DECIMAL(15,8),    
    RET_MXN_TRASLADAR_FACT DECIMAL(15,2),
    RET_MXN_TRASLADAR_DEP DECIMAL(15,2),
    PERDIDA_GANANCIA DECIMAL(15,2),
    CUENTA_PER_GANANCIA VARCHAR(30),
    FECHA VARCHAR(10),
    CLIENTE VARCHAR(120),
    SITE_ID VARCHAR(15));

	CREATE TABLE #POLIZASNEGATIVAS( 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO INT,
    SITE_ID VARCHAR(15));
	
	IF (@CONSILIADO = 1)
	BEGIN
		-- Obtener todos los movimientos consiliados RETENCION		
		INSERT #POLIZASCXP(SITE_ID, BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, RET_MXN_TRASLADAR_FACT, TC_DEPOSITO, RET_MXN_TRASLADAR_DEP, PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE)
			SELECT	A.SITE_ID
				, A.BANK_ACCOUNT_ID 
				,A.CONTROL_NO 
				,A.GL_ACCOUNT_ID
				,B.DESCRIPCION
				,B.TRASLADO
				,A.TC_FACTURA
				,CASE 
					WHEN SUM(A.RETENCION_MXN_FACT) = 0.01 THEN 0 
					WHEN SUM(A.RETENCION_MXN_FACT) = -0.01 THEN 0 
				ELSE SUM(A.RETENCION_MXN_FACT)  END
				,A.TC_Pago				
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN A.RETENCION_MXN_PAGO + 0.01
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN A.RETENCION_MXN_PAGO - 0.01
				ELSE SUM(A.RETENCION_MXN_PAGO) END AS RET_MXN_TRASLADAR_DEP	
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN 0 
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN 0 
				ELSE SUM(A.GANANCIA_PERDIDA)END
				,A.CUENTA_PER_GANANCIA
				,@FECHA
				,A.VENDOR_ID
			FROM VMX_IVA_TRASL_CXP_03 AS a,VMX_CUENTAS_RETENCION AS b 
			WHERE b.Cuenta =  a.GL_ACCOUNT_ID AND b.Estado = 'True' 
				AND a.ANIO_CONCILIACION = @ANIO
				AND a.MES_CONCILIACION = @MES	
				AND a.SITE_ID = @SITE_ID			
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO,a.GL_ACCOUNT_ID,b.Descripcion,a.TC_FACTURA,b.Traslado,A.RETENCION_MXN_FACT,A.TC_Pago,A.RETENCION_MXN_PAGO,A.GANANCIA_PERDIDA,A.CUENTA_PER_GANANCIA,a.VENDOR_ID
			
			-- Obtener los movimientos con montos negativos retencion
			INSERT #POLIZASNEGATIVAS(SITE_ID,BANK_ACCOUNT_ID,CONTROL_NO)
				SELECT A.SITE_ID, A.BANK_ACCOUNT_ID,A.CONTROL_NO      
				FROM VMX_IVA_TRASL_CXP_03 AS a,VMX_CUENTAS_RETENCION AS b 
				WHERE b.Cuenta =  a.GL_ACCOUNT_ID AND b.Estado = 'True' 
					-- Consiliados
					AND a.ANIO_CONCILIACION = @ANIO AND a.MES_CONCILIACION = @MES AND a.SITE_ID = @SITE_ID
				GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO	,a.GL_ACCOUNT_ID        
				HAVING CASE WHEN SUM(A.RETENCION_MXN_FACT) = 0.01 THEN 0 WHEN SUM(A.RETENCION_MXN_FACT) = -0.01 THEN 0 ELSE SUM(A.RETENCION_MXN_FACT)END < 0

	END
	ELSE
	BEGIN
		-- Obtener todos los movimientos consiliados y no consiliados RETENCION
		INSERT #POLIZASCXP(SITE_ID, BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, RET_MXN_TRASLADAR_FACT, TC_DEPOSITO, RET_MXN_TRASLADAR_DEP, PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE)
			SELECT A.SITE_ID
				,A.BANK_ACCOUNT_ID 
				,A.CONTROL_NO 
				,A.GL_ACCOUNT_ID
				,B.DESCRIPCION
				,B.TRASLADO
				,A.TC_FACTURA
				-- Hacer cero el monto, cuando el Monto de RETENCION prorrateado sea un centavo positivo o negativo.
				,CASE 
					WHEN SUM(A.RETENCION_MXN_FACT) = 0.01 THEN 0 
					WHEN SUM(A.RETENCION_MXN_FACT) = -0.01 THEN 0 
				ELSE SUM(A.RETENCION_MXN_FACT)  END
				,A.TC_Pago				
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN A.RETENCION_MXN_PAGO + 0.01
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN A.RETENCION_MXN_PAGO - 0.01
				ELSE SUM(A.RETENCION_MXN_PAGO) END AS RET_MXN_TRASLADAR_DEP	
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN 0 
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN 0 
				ELSE SUM(A.GANANCIA_PERDIDA)END
				,A.CUENTA_PER_GANANCIA
				,@FECHA
				,A.VENDOR_ID
			FROM VMX_IVA_TRASL_CXP_03 AS a,VMX_CUENTAS_RETENCION AS b 
			WHERE b.Cuenta =  a.GL_ACCOUNT_ID
				AND b.Estado = 'True'
				AND a.ANIO_POSTEO = @ANIO
				AND a.MES_POSTEO = @MES
				AND a.SITE_ID = @SITE_ID
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO,a.GL_ACCOUNT_ID,b.Descripcion,a.TC_FACTURA,b.Traslado,A.RETENCION_MXN_FACT,
				A.TC_Pago,A.RETENCION_MXN_PAGO,A.GANANCIA_PERDIDA,A.CUENTA_PER_GANANCIA,a.VENDOR_ID
		
		-- Obtener los movimientos con montos negativos RETENCION
		INSERT #POLIZASNEGATIVAS(SITE_ID, BANK_ACCOUNT_ID,CONTROL_NO)
			SELECT A.SITE_ID, A.BANK_ACCOUNT_ID,A.CONTROL_NO      
			FROM VMX_IVA_TRASL_CXP_03 AS a,VMX_DIOTCUENTAS AS b 
			WHERE b.Cuenta =  a.GL_ACCOUNT_ID AND b.Estado = 'True' 
				-- No Consiliados
				AND a.ANIO_POSTEO = @ANIO AND a.MES_POSTEO = @MES AND a.SITE_ID = @SITE_ID
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO	,a.GL_ACCOUNT_ID        
			HAVING CASE WHEN SUM(A.RETENCION_MXN_FACT) = 0.01 THEN 0 WHEN SUM(A.RETENCION_MXN_FACT) = -0.01 THEN 0 ELSE SUM(A.RETENCION_MXN_FACT)END < 0
	END		
    
    -- Eliminar las polizas negativas. Filtrar por Banco y No. Control                        
	DELETE FROM #POLIZASCXP 
	FROM #POLIZASCXP AS P LEFT JOIN #POLIZASNEGATIVAS AS N ON P.BANK_ACCOUNT_ID = N.BANK_ACCOUNT_ID AND P.CONTROL_NO = N.CONTROL_NO AND P.SITE_ID = N.SITE_ID
	WHERE N.BANK_ACCOUNT_ID IS NOT NULL AND N.CONTROL_NO IS NOT NULL
	
	-- Eliminar las polizas que han completado el traspaso de RETENCION.
	DELETE FROM #POLIZASCXP
	FROM #POLIZASCXP AS P 
		LEFT JOIN VMX_CONTOLPOLIZA_LINE AS PL 
			ON P.BANK_ACCOUNT_ID = PL.BANK_ACCOUNT_ID AND P.CONTROL_NO = PL.CONTROL_NO AND P.VAT_GL_ACCT_ID = PL.CUENTA AND P.SITE_ID = PL.SITE_ID AND PL.CUSTOMER_ID = P.CLIENTE
	WHERE PL.BANK_ACCOUNT_ID IS NOT NULL AND PL.CONTROL_NO IS NOT NULL AND PL.CUENTA IS NOT NULL
		AND PL.TIPO_OPERACION = 'CXP'
	
	SELECT SITE_ID
		,BANK_ACCOUNT_ID
		,CONTROL_NO
		,CLIENTE
		,VAT_GL_ACCT_ID
		,DESCRIPCION
		,TRASLADO
		,TC_FACTURA
		,TC_DEPOSITO
		,0.00 IVA_MXN_TRASLADAR_FACT
		,0.00 IVA_MXN_TRASLADAR_DEP
		,ISNULL(RET_MXN_TRASLADAR_FACT,0.0) AS RET_MXN_TRASLADAR_FACT
		,ISNULL(RET_MXN_TRASLADAR_DEP,0.0) AS RET_MXN_TRASLADAR_DEP
		,ISNULL(PERDIDA_GANANCIA,0.0) AS PERDIDA_GANANCIA
		,CUENTA_PER_GANANCIA
		,FECHA
	FROM #POLIZASCXP
	ORDER BY BANK_ACCOUNT_ID,CONTROL_NO

	DROP TABLE #POLIZASCXP                    
	DROP TABLE #POLIZASNEGATIVAS
GO

GRANT EXECUTE ON dbo.[PRC_POLIZAS_POR_TRASPASAR_RET_CXP] TO PUBLIC
GO

--	[PRC_POLIZAS_POR_TRASPASAR_CXC_DET]

IF OBJECT_ID ( 'PRC_POLIZAS_POR_TRASPASAR_CXC_DET', 'P' ) IS NOT NULL 
    DROP PROCEDURE dbo.PRC_POLIZAS_POR_TRASPASAR_CXC_DET;
GO
CREATE PROCEDURE [dbo].[PRC_POLIZAS_POR_TRASPASAR_CXC_DET] (@ANIO INT,@MES INT, @FECHA VARCHAR(15),@CONSILIADO INT, @SITE_ID VARCHAR(15))
AS

	SET NOCOUNT ON;
  
    CREATE TABLE #POLIZASCXC(	 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO VARCHAR(15),
    VAT_GL_ACCT_ID VARCHAR(30),
    DESCRIPCION VARCHAR(200),
    TRASLADO VARCHAR(30),
    TC_FACTURA DECIMAL(15,8),
    TC_DEPOSITO DECIMAL(15,8),    
    IVA_MXN_TRASLADAR_FACT DECIMAL(15,2),
    IVA_MXN_TRASLADAR_DEP DECIMAL(15,2),
    PERDIDA_GANANCIA DECIMAL(15,2),
    CUENTA_PER_GANANCIA VARCHAR(30),
    FECHA VARCHAR(10),
    CLIENTE VARCHAR(120),
    SITE_ID VARCHAR(15),
    INVOICE VARCHAR(15),
    INVOICE_LN VARCHAR(10),
    RFC VARCHAR(25),
    NAME VARCHAR(50),
	AMOUNT DECIMAL(15,2));
    
	CREATE TABLE #POLIZASNEGATIVAS( 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO VARCHAR(15),
    SITE_ID VARCHAR(15));
	
	IF (@CONSILIADO = 1)
	BEGIN
		-- Obtener todos los movimientos consiliados
		INSERT #POLIZASCXC(SITE_ID,BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, IVA_MXN_TRASLADAR_FACT, TC_DEPOSITO, IVA_MXN_TRASLADAR_DEP, PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE,
			RFC,NAME,INVOICE,INVOICE_LN,AMOUNT)
			SELECT C.SITE_ID, C.BANK_ACCOUNT_ID
				,C.CHECK_ID
                ,C.VAT_GL_ACCT_ID
                ,CTA.DESCRIPCION
                ,CTA.TRASLADO
                ,TC_FACTURA
                -- Hacer cero el monto, cuando el Monto de IVA prorrateado sea un centavo positivo o negativo.
                ,CASE 
					WHEN SUM(C.IVA_MXN_TRASLADAR_FACT) = 0.01 THEN 0 
					WHEN SUM(C.IVA_MXN_TRASLADAR_FACT) = -0.01 THEN 0 
				ELSE SUM(C.IVA_MXN_TRASLADAR_FACT)END                             
				,TC_DEPOSITO				
				,CASE 
					WHEN SUM(PERDIDA_GANANCIA) = 0.01 THEN IVA_MXN_TRASLADAR_DEP - 0.01
					WHEN SUM(PERDIDA_GANANCIA) = -0.01 THEN IVA_MXN_TRASLADAR_DEP + 0.01
				ELSE SUM(IVA_MXN_TRASLADAR_DEP) END AS IVA_MXN_TRASLADAR_DEP							
				,CASE 
					WHEN SUM(PERDIDA_GANANCIA) = 0.01 THEN 0 
					WHEN SUM(PERDIDA_GANANCIA) = -0.01 THEN 0 
				ELSE SUM(PERDIDA_GANANCIA)END									
				,CUENTA_PER_GANANCIA			
				,@FECHA
				,C.COD_CLIENTE
				,ISNULL(CUST.VAT_REGISTRATION,'')
				,ISNULL(CUST.NAME,'')
				,C.FACTURA
				,C.LINE_NO
				,C.AMOUNT
			FROM ACCOUNT AS A, VMX_IVACUENTASCXC AS CTA,VMX_IVA_CXC_02 AS C
			LEFT JOIN CUSTOMER CUST ON CUST.ID = C.COD_CLIENTE
			WHERE CTA.Traslado = A.ID
				AND CTA.Cuenta = C.VAT_GL_ACCT_ID
				AND CTA.Estado = 'True'
				AND C.Anio_Conc = @ANIO
				AND C.Mes_conc = @MES
				AND C.SITE_ID = @SITE_ID
            GROUP BY C.SITE_ID, C.BANK_ACCOUNT_ID,C.CHECK_ID,C.VAT_GL_ACCT_ID,CTA.Descripcion,CUST.VAT_REGISTRATION,CUST.NAME
				,C.TC_FACTURA,CTA.Traslado,A.DESCRIPTION,C.Cod_Cliente,TC_DEPOSITO
				,IVA_MXN_TRASLADAR_DEP
				,PERDIDA_GANANCIA
				,CUENTA_PER_GANANCIA
				,ISNULL(CUST.VAT_REGISTRATION,'')
				,ISNULL(CUST.NAME,'')
				,C.FACTURA
				,C.LINE_NO
				,C.AMOUNT
			
			-- Obtener los movimientos con montos negativos
			INSERT #POLIZASNEGATIVAS(SITE_ID, BANK_ACCOUNT_ID,CONTROL_NO)
			SELECT CXC.SITE_ID, CXC.BANK_ACCOUNT_ID,CXC.CHECK_ID
			FROM ACCOUNT AS AC, VMX_IVA_CXC_02 AS CXC, VMX_IVACUENTASCXC AS CTAS
			WHERE CTAS.Traslado = AC.ID
				AND CTAS.Cuenta = CXC.VAT_GL_ACCT_ID
				AND CTAS.Estado = 'True'
				AND CXC.Anio_Conc = @ANIO
				AND CXC.Mes_conc = @MES
				AND CXC.SITE_ID = @SITE_ID
			GROUP BY CXC.SITE_ID, CXC.BANK_ACCOUNT_ID,CXC.CHECK_ID,CXC.VAT_GL_ACCT_ID
			HAVING CASE WHEN SUM(CXC.IVA_MXN_TRASLADAR_FACT) = 0.01 THEN 0 WHEN SUM(CXC.IVA_MXN_TRASLADAR_FACT) = -0.01 THEN 0 ELSE SUM(CXC.IVA_MXN_TRASLADAR_FACT) END < 0
	END
	ELSE
	BEGIN
		-- Obtener todos los movimientos consiliados y no consiliados
		INSERT #POLIZASCXC(SITE_ID, BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, IVA_MXN_TRASLADAR_FACT, TC_DEPOSITO, IVA_MXN_TRASLADAR_DEP, PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE,
			RFC,NAME,INVOICE,INVOICE_LN,AMOUNT)
			SELECT C.SITE_ID 
				,C.BANK_ACCOUNT_ID
				,C.CHECK_ID
                ,C.VAT_GL_ACCT_ID
                ,CTA.DESCRIPCION
                ,CTA.TRASLADO
                ,TC_FACTURA
                -- Hacer cero el monto, cuando el Monto de IVA prorrateado sea un centavo positivo o negativo.
                ,CASE WHEN SUM(C.IVA_MXN_TRASLADAR_FACT) = 0.01 THEN 0 
					WHEN SUM(C.IVA_MXN_TRASLADAR_FACT) = -0.01 THEN 0 ELSE SUM(C.IVA_MXN_TRASLADAR_FACT)END                             
				,TC_DEPOSITO				
				,CASE 
					WHEN SUM(PERDIDA_GANANCIA) = 0.01 THEN IVA_MXN_TRASLADAR_DEP - 0.01
					WHEN SUM(PERDIDA_GANANCIA) = -0.01 THEN IVA_MXN_TRASLADAR_DEP + 0.01
				ELSE IVA_MXN_TRASLADAR_DEP END AS IVA_MXN_TRASLADAR_DEP							
				,CASE WHEN SUM(PERDIDA_GANANCIA) = 0.01 THEN 0 
					WHEN SUM(PERDIDA_GANANCIA) = -0.01 THEN 0 ELSE SUM(PERDIDA_GANANCIA)END									
				,CUENTA_PER_GANANCIA
				,@FECHA
				,C.COD_CLIENTE
				,CUST.VAT_REGISTRATION
				,CUST.NAME
				,C.FACTURA
				,C.LINE_NO
				,C.AMOUNT
			FROM ACCOUNT AS A, VMX_IVACUENTASCXC AS CTA,VMX_IVA_CXC_02 AS C
			LEFT JOIN CUSTOMER CUST ON CUST.ID = C.COD_CLIENTE
			WHERE CTA.Traslado = A.ID
				AND CTA.Cuenta = C.VAT_GL_ACCT_ID
				AND CTA.Estado = 'True'
				AND C.ANIO_POSTEO = @ANIO
				AND C.MES_POSTEO = @MES
				AND C.SITE_ID = @SITE_ID
            GROUP BY C.SITE_ID, C.BANK_ACCOUNT_ID,C.CHECK_ID,C.VAT_GL_ACCT_ID,CTA.Descripcion
				,C.TC_FACTURA,CTA.Traslado,A.DESCRIPTION,C.Cod_Cliente,TC_DEPOSITO
				,IVA_MXN_TRASLADAR_DEP
				,PERDIDA_GANANCIA
				,CUENTA_PER_GANANCIA
				,CUST.VAT_REGISTRATION,CUST.NAME
				,C.FACTURA
				,C.LINE_NO
				,C.AMOUNT
		
		-- Obtener los movimientos con montos negativos
		INSERT #POLIZASNEGATIVAS(SITE_ID, BANK_ACCOUNT_ID,CONTROL_NO)
			SELECT CXC.SITE_ID, CXC.BANK_ACCOUNT_ID,CXC.CHECK_ID
			FROM ACCOUNT AS AC, VMX_IVA_CXC_02 AS CXC, VMX_IVACUENTASCXC AS CTAS
			WHERE CTAS.Traslado = AC.ID
				AND CTAS.Cuenta = CXC.VAT_GL_ACCT_ID
				AND CTAS.Estado = 'True'
				AND CXC.ANIO_POSTEO = @ANIO
				AND CXC.MES_POSTEO = @MES
				AND CXC.SITE_ID = @SITE_ID
			GROUP BY CXC.SITE_ID, CXC.BANK_ACCOUNT_ID,CXC.CHECK_ID,CXC.VAT_GL_ACCT_ID    
			HAVING CASE WHEN SUM(CXC.IVA_MXN_TRASLADAR_FACT) = 0.01 THEN 0 WHEN SUM(CXC.IVA_MXN_TRASLADAR_FACT) = -0.01 THEN 0 ELSE SUM(CXC.IVA_MXN_TRASLADAR_FACT) END < 0
	END		
    
    -- Eliminar las polizas negativas. Filtrar por Banco y No. Control                        
	DELETE FROM #POLIZASCXC
	FROM #POLIZASCXC AS P LEFT JOIN #POLIZASNEGATIVAS AS N ON P.BANK_ACCOUNT_ID = N.BANK_ACCOUNT_ID AND P.CONTROL_NO = N.CONTROL_NO AND P.SITE_ID = N.SITE_ID
	WHERE N.BANK_ACCOUNT_ID IS NOT NULL AND N.CONTROL_NO IS NOT NULL
	
	-- Eliminar las polizas que han completado el traspaso de IVA.
	DELETE FROM #POLIZASCXC
	FROM #POLIZASCXC AS P 
		LEFT JOIN VMX_CONTOLPOLIZA_LINE AS PL 
			ON P.BANK_ACCOUNT_ID = PL.BANK_ACCOUNT_ID AND P.CONTROL_NO = PL.CHECK_ID AND P.SITE_ID = PL.SITE_ID AND PL.CUSTOMER_ID = P.CLIENTE --AND P.VAT_GL_ACCT_ID = PL.CUENTA
	WHERE PL.BANK_ACCOUNT_ID IS NOT NULL AND PL.CHECK_ID IS NOT NULL AND PL.CUENTA IS NOT NULL
		AND PL.TIPO_OPERACION = 'CXC'
		   
	SELECT SITE_ID
		,BANK_ACCOUNT_ID Banco
		,CONTROL_NO "No. Control"
		,CLIENTE Cliente
		,RFC
		,NAME Nombre
		,INVOICE Factura
		,INVOICE_LN "Linea Factura"
		,VAT_GL_ACCT_ID Cuenta
		,DESCRIPCION "Descripción"
		,TRASLADO "Cuenta Traslado"
		,AMOUNT Monto
		,TC_FACTURA "Tipo Cambio Factura"
		,TC_DEPOSITO "Tipo Cambio Depósito"
		,ISNULL(IVA_MXN_TRASLADAR_FACT,0.0) AS "IVA Factura"
		,ISNULL(IVA_MXN_TRASLADAR_DEP,0.0) AS "IVA Deposito"
		,ISNULL(PERDIDA_GANANCIA,0.0) AS "Perdida Ganancia"
		,CUENTA_PER_GANANCIA "Cuenta Perdida Ganancia"
		,FECHA Fecha
	FROM #POLIZASCXC
	ORDER BY BANK_ACCOUNT_ID,CONTROL_NO,INVOICE,INVOICE_LN

	DROP TABLE #POLIZASCXC
	DROP TABLE #POLIZASNEGATIVAS

GO

GRANT EXECUTE ON dbo.PRC_POLIZAS_POR_TRASPASAR_CXC_DET TO PUBLIC
GO


--	[PRC_POLIZAS_POR_TRASPASAR_CXP_DET]

IF OBJECT_ID ( 'PRC_POLIZAS_POR_TRASPASAR_CXP_DET', 'P' ) IS NOT NULL 
    DROP PROCEDURE dbo.PRC_POLIZAS_POR_TRASPASAR_CXP_DET;
GO
CREATE PROCEDURE [dbo].[PRC_POLIZAS_POR_TRASPASAR_CXP_DET] (@ANIO INT,@MES INT, @FECHA VARCHAR(15),@CONSILIADO INT, @SITE_ID VARCHAR(15))
AS

	SET NOCOUNT ON;
  CREATE TABLE #POLIZASCXP(	 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO INT,
    VAT_GL_ACCT_ID VARCHAR(30),
    DESCRIPCION VARCHAR(200),
    TRASLADO VARCHAR(30),
    TC_FACTURA DECIMAL(15,8),
    TC_DEPOSITO DECIMAL(15,8),    
    IVA_MXN_TRASLADAR_FACT DECIMAL(15,2),
    IVA_MXN_TRASLADAR_DEP DECIMAL(15,2),
    RET_MXN_TRASLADAR_FACT DECIMAL(15,2),
    RET_MXN_TRASLADAR_DEP DECIMAL(15,2),
    PERDIDA_GANANCIA DECIMAL(15,2),
    CUENTA_PER_GANANCIA VARCHAR(30),
    FECHA VARCHAR(10),
    CLIENTE VARCHAR(120),
    SITE_ID VARCHAR(15),
    VOUCHER VARCHAR(15),
    VOUCHER_LN VARCHAR(10),
    RFC VARCHAR(25),
    NAME VARCHAR(50),
    AMOUNT DECIMAL(15,2),
    INVOICE_ID VARCHAR(15)
    );

	CREATE TABLE #POLIZASNEGATIVAS( 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO INT,
    SITE_ID VARCHAR(15));
	
	IF (@CONSILIADO = 1)
	BEGIN
		-- Obtener todos los movimientos consiliados		
		INSERT #POLIZASCXP(SITE_ID, BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, IVA_MXN_TRASLADAR_FACT,RET_MXN_TRASLADAR_FACT, TC_DEPOSITO, IVA_MXN_TRASLADAR_DEP, RET_MXN_TRASLADAR_DEP,PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE
			,VOUCHER,VOUCHER_LN,RFC,NAME,AMOUNT,INVOICE_ID)
			SELECT A.SITE_ID
				, A.BANK_ACCOUNT_ID 
				,A.CONTROL_NO 
				,A.VAT_GL_ACCT_ID
				,B.DESCRIPCION
				,B.TRASLADO
				,A.TC_FACTURA
				-- Hacer cero el monto, cuando el Monto de IVA prorrateado sea un centavo positivo o negativo.
				,CASE 
					WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = 0.01 THEN 0 
					WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = -0.01 THEN 0 
				ELSE SUM(A.IVA_TRASLADO_MXN_FACT)  END
				,0
				,A.TC_Pago				
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN A.IVA_TRASLADO_MXN_PAGO + 0.01
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN A.IVA_TRASLADO_MXN_PAGO - 0.01
				ELSE SUM(A.IVA_TRASLADO_MXN_PAGO) END AS IVA_MXN_TRASLADAR_DEP	
				,0
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN 0 
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN 0 
				ELSE SUM(A.GANANCIA_PERDIDA)END
				,A.CUENTA_PER_GANANCIA
				,@FECHA
				,A.VENDOR_ID
				,A.VOUCHER_ID
				,A.LINE_NO
				,isnull(V.VAT_REGISTRATION,'')
				,V.NAME
				,A.AMOUNT
				,A.INVOICE_ID
			FROM VMX_DIOTCUENTAS AS b,VMX_IVA_TRASL_CXP_02 AS a --CASH_DISBURSE
			INNER JOIN VENDOR V ON V.ID = A.VENDOR_ID
			WHERE b.Cuenta =  a.VAT_GL_ACCT_ID
				AND b.Estado = 'True'
				AND a.ANIO_CONCILIACION = @ANIO
				AND a.MES_CONCILIACION = @MES	
				AND a.SITE_ID = @SITE_ID			
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO,a.VAT_GL_ACCT_ID,b.Descripcion,a.TC_FACTURA,b.Traslado,A.IVA_TRASLADO_MXN_FACT,
				A.TC_Pago,A.IVA_TRASLADO_MXN_PAGO,A.GANANCIA_PERDIDA,A.CUENTA_PER_GANANCIA,a.VENDOR_ID
				,A.VOUCHER_ID
				,A.LINE_NO
				,V.VAT_REGISTRATION
				,V.NAME
				,AMOUNT
				,A.INVOICE_ID
				
			-- Obtener los movimientos con montos negativos
			INSERT #POLIZASNEGATIVAS(SITE_ID,BANK_ACCOUNT_ID,CONTROL_NO)
				SELECT A.SITE_ID, A.BANK_ACCOUNT_ID,A.CONTROL_NO      
				FROM VMX_IVA_TRASL_CXP_02 AS a,VMX_DIOTCUENTAS AS b 
				WHERE b.Cuenta =  a.VAT_GL_ACCT_ID AND b.Estado = 'True' 
					-- Consiliados
					AND a.ANIO_CONCILIACION = @ANIO AND a.MES_CONCILIACION = @MES AND a.SITE_ID = @SITE_ID
				GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO	,a.VAT_GL_ACCT_ID        
				HAVING CASE WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = 0.01 THEN 0 WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = -0.01 THEN 0 ELSE SUM(A.IVA_TRASLADO_MXN_FACT)END < 0
	END
	ELSE
	BEGIN
		-- Obtener todos los movimientos consiliados y no consiliados
		INSERT #POLIZASCXP(SITE_ID, BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, IVA_MXN_TRASLADAR_FACT, RET_MXN_TRASLADAR_FACT,TC_DEPOSITO, IVA_MXN_TRASLADAR_DEP,RET_MXN_TRASLADAR_DEP, PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE
			,VOUCHER,VOUCHER_LN,RFC,NAME,AMOUNT,INVOICE_ID)
			SELECT A.SITE_ID
				,A.BANK_ACCOUNT_ID 
				,A.CONTROL_NO 
				,A.VAT_GL_ACCT_ID
				,B.DESCRIPCION
				,B.TRASLADO
				,A.TC_FACTURA
				-- Hacer cero el monto, cuando el Monto de IVA prorrateado sea un centavo positivo o negativo.
				,CASE 
					WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = 0.01 THEN 0 
					WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = -0.01 THEN 0 
				ELSE SUM(A.IVA_TRASLADO_MXN_FACT)  END
				,0
				,A.TC_Pago				
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN A.IVA_TRASLADO_MXN_PAGO + 0.01
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN A.IVA_TRASLADO_MXN_PAGO - 0.01
				ELSE SUM(A.IVA_TRASLADO_MXN_PAGO) END AS IVA_MXN_TRASLADAR_DEP	
				,0
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN 0 
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN 0 
				ELSE SUM(A.GANANCIA_PERDIDA)END
				,A.CUENTA_PER_GANANCIA
				,@FECHA
				,A.VENDOR_ID
				,A.VOUCHER_ID
				,A.LINE_NO
				,isnull(V.VAT_REGISTRATION,'')
				,V.NAME
				,A.AMOUNT
				,A.INVOICE_ID
			FROM VMX_DIOTCUENTAS AS b,VMX_IVA_TRASL_CXP_02 AS a --CASH_DISBURSE
			INNER JOIN VENDOR V ON V.ID = A.VENDOR_ID
			WHERE b.Cuenta =  a.VAT_GL_ACCT_ID
				AND b.Estado = 'True'
				AND a.ANIO_POSTEO = @ANIO
				AND a.MES_POSTEO = @MES
				AND a.SITE_ID = @SITE_ID
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO,a.VAT_GL_ACCT_ID,b.Descripcion,a.TC_FACTURA,b.Traslado,A.IVA_TRASLADO_MXN_FACT,
				A.TC_Pago,A.IVA_TRASLADO_MXN_PAGO,A.GANANCIA_PERDIDA,A.CUENTA_PER_GANANCIA,a.VENDOR_ID
				,A.VOUCHER_ID
				,A.LINE_NO
				,V.VAT_REGISTRATION
				,V.NAME
				,AMOUNT
				,A.INVOICE_ID
		
		-- Obtener los movimientos con montos negativos
		INSERT #POLIZASNEGATIVAS(SITE_ID, BANK_ACCOUNT_ID,CONTROL_NO)
			SELECT A.SITE_ID, A.BANK_ACCOUNT_ID,A.CONTROL_NO      
			FROM VMX_IVA_TRASL_CXP_02 AS a,VMX_DIOTCUENTAS AS b --CASH_DISBURSE
			WHERE b.Cuenta =  a.VAT_GL_ACCT_ID AND b.Estado = 'True' 
				-- No Consiliados
				AND a.ANIO_POSTEO = @ANIO AND a.MES_POSTEO = @MES AND a.SITE_ID = @SITE_ID
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO	,a.VAT_GL_ACCT_ID        
			HAVING CASE WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = 0.01 THEN 0 WHEN SUM(A.IVA_TRASLADO_MXN_FACT) = -0.01 THEN 0 ELSE SUM(A.IVA_TRASLADO_MXN_FACT)END < 0
	END		
    
    -- Eliminar las polizas negativas. Filtrar por Banco y No. Control                        
	DELETE FROM #POLIZASCXP 
	FROM #POLIZASCXP AS P LEFT JOIN #POLIZASNEGATIVAS AS N ON P.BANK_ACCOUNT_ID = N.BANK_ACCOUNT_ID AND P.CONTROL_NO = N.CONTROL_NO AND P.SITE_ID = N.SITE_ID
	WHERE N.BANK_ACCOUNT_ID IS NOT NULL AND N.CONTROL_NO IS NOT NULL
	
	-- Eliminar las polizas que han completado el traspaso de IVA.
	DELETE FROM #POLIZASCXP
	FROM #POLIZASCXP AS P 
		LEFT JOIN VMX_CONTOLPOLIZA_LINE AS PL 
			ON P.BANK_ACCOUNT_ID = PL.BANK_ACCOUNT_ID AND P.CONTROL_NO = PL.CONTROL_NO AND P.VAT_GL_ACCT_ID = PL.CUENTA AND P.SITE_ID = PL.SITE_ID AND PL.CUSTOMER_ID = P.CLIENTE
	WHERE PL.BANK_ACCOUNT_ID IS NOT NULL AND PL.CONTROL_NO IS NOT NULL AND PL.CUENTA IS NOT NULL
		AND PL.TIPO_OPERACION = 'CXP'
	
	SELECT SITE_ID
		,BANK_ACCOUNT_ID AS Banco
		,CONTROL_NO AS "No. Control"
		,CLIENTE AS Proveedor
		,RFC AS "RFC"
		,NAME AS "Nombre Proveedor"
		,VAT_GL_ACCT_ID AS Cuenta
		,DESCRIPCION AS "Descripción"
		,TRASLADO AS "Cuenta Traslado"
		,VOUCHER AS Voucher
		,VOUCHER_LN AS "Linea Voucher"
		,INVOICE_ID AS Factura
		,AMOUNT AS Monto
		,TC_FACTURA AS "Tipo Cambio Factura"
		,TC_DEPOSITO AS "Tipo Cambio Deposito"
		,ISNULL(IVA_MXN_TRASLADAR_FACT,0.0) AS "IVA Factura"
		,ISNULL(IVA_MXN_TRASLADAR_DEP,0.0) AS "IVA Deposito"
		,ISNULL(RET_MXN_TRASLADAR_FACT,0.0) AS "Retención Factura"
		,ISNULL(RET_MXN_TRASLADAR_DEP,0.0) AS "Retención Deposito"
		,ISNULL(PERDIDA_GANANCIA,0.0) AS "Perdida Ganancia"
		,CUENTA_PER_GANANCIA AS "Cuenta Perdida Ganancia"
		,FECHA AS Fecha

	FROM #POLIZASCXP 
	ORDER BY BANK_ACCOUNT_ID,CONTROL_NO,VOUCHER,VOUCHER_LN

	DROP TABLE #POLIZASCXP                    
	DROP TABLE #POLIZASNEGATIVAS


GO

GRANT EXECUTE ON dbo.PRC_POLIZAS_POR_TRASPASAR_CXP_DET TO PUBLIC
GO

--	[PRC_POLIZAS_POR_TRASPASAR_RET_CXP_DET]

IF OBJECT_ID ( 'PRC_POLIZAS_POR_TRASPASAR_RET_CXP_DET', 'P' ) IS NOT NULL 
    DROP PROCEDURE dbo.PRC_POLIZAS_POR_TRASPASAR_RET_CXP_DET;
GO
CREATE PROCEDURE [dbo].[PRC_POLIZAS_POR_TRASPASAR_RET_CXP_DET] (@ANIO INT,@MES INT, @FECHA VARCHAR(15),@CONSILIADO INT, @SITE_ID VARCHAR(15))
AS
	SET NOCOUNT ON;

    CREATE TABLE #POLIZASCXP(	 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO INT,
    VAT_GL_ACCT_ID VARCHAR(30),
    DESCRIPCION VARCHAR(200),
    TRASLADO VARCHAR(30),
    TC_FACTURA DECIMAL(15,8),
    TC_DEPOSITO DECIMAL(15,8),    
    IVA_MXN_TRASLADAR_FACT DECIMAL(15,2),
    IVA_MXN_TRASLADAR_DEP DECIMAL(15,2),
    RET_MXN_TRASLADAR_FACT DECIMAL(15,2),
    RET_MXN_TRASLADAR_DEP DECIMAL(15,2),
    PERDIDA_GANANCIA DECIMAL(15,2),
    CUENTA_PER_GANANCIA VARCHAR(30),
    FECHA VARCHAR(10),
    CLIENTE VARCHAR(120),
    SITE_ID VARCHAR(15),
    VOUCHER VARCHAR(15),
    VOUCHER_LN VARCHAR(10),
    RFC VARCHAR(25),
    NAME VARCHAR(50),
    AMOUNT DECIMAL(15,2),
    INVOICE_ID VARCHAR(15)
    );

	CREATE TABLE #POLIZASNEGATIVAS( 
	BANK_ACCOUNT_ID VARCHAR(15),
    CONTROL_NO INT,
    SITE_ID VARCHAR(15));
	
	IF (@CONSILIADO = 1)
	BEGIN
		-- Obtener todos los movimientos consiliados RETENCION		
		INSERT #POLIZASCXP(SITE_ID, BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, IVA_MXN_TRASLADAR_FACT,RET_MXN_TRASLADAR_FACT, TC_DEPOSITO, IVA_MXN_TRASLADAR_DEP,RET_MXN_TRASLADAR_DEP, PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE
			,VOUCHER,VOUCHER_LN,RFC,NAME,AMOUNT,INVOICE_ID)
			SELECT	A.SITE_ID
				, A.BANK_ACCOUNT_ID 
				,A.CONTROL_NO 
				,A.GL_ACCOUNT_ID
				,B.DESCRIPCION
				,B.TRASLADO
				,A.TC_FACTURA
				,0 --IVA no aplica por que es retención
				,CASE 
					WHEN SUM(A.RETENCION_MXN_FACT) = 0.01 THEN 0 
					WHEN SUM(A.RETENCION_MXN_FACT) = -0.01 THEN 0 
				ELSE SUM(A.RETENCION_MXN_FACT)  END RET_MXN_TRASLADAR_FACT
				,A.TC_Pago	
				,0 --IVA no aplica por que es retención			
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN A.RETENCION_MXN_PAGO + 0.01
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN A.RETENCION_MXN_PAGO - 0.01
				ELSE SUM(A.RETENCION_MXN_PAGO) END AS RET_MXN_TRASLADAR_DEP	
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN 0 
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN 0 
				ELSE SUM(A.GANANCIA_PERDIDA)END
				,A.CUENTA_PER_GANANCIA
				,@FECHA
				,A.VENDOR_ID
				,A.VOUCHER_ID
				,A.LINE_NO
				,isnull(V.VAT_REGISTRATION,'')
				,V.NAME
				,A.AMOUNT
				,A.INVOICE_ID
			FROM VMX_CUENTAS_RETENCION AS b,VMX_IVA_TRASL_CXP_03 AS a
			INNER JOIN VENDOR V ON V.ID = A.VENDOR_ID
			WHERE b.Cuenta =  a.GL_ACCOUNT_ID AND b.Estado = 'True' 
				AND a.ANIO_CONCILIACION = @ANIO
				AND a.MES_CONCILIACION = @MES	
				AND a.SITE_ID = @SITE_ID			
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO,a.GL_ACCOUNT_ID,b.Descripcion,a.TC_FACTURA,b.Traslado,A.RETENCION_MXN_FACT,A.TC_Pago,A.RETENCION_MXN_PAGO,A.GANANCIA_PERDIDA,A.CUENTA_PER_GANANCIA,a.VENDOR_ID
				,A.VOUCHER_ID
				,A.LINE_NO
				,V.VAT_REGISTRATION
				,V.NAME
				,A.AMOUNT
				,A.INVOICE_ID
			
			-- Obtener los movimientos con montos negativos retencion
			INSERT #POLIZASNEGATIVAS(SITE_ID,BANK_ACCOUNT_ID,CONTROL_NO)
				SELECT A.SITE_ID, A.BANK_ACCOUNT_ID,A.CONTROL_NO      
				FROM VMX_IVA_TRASL_CXP_03 AS a,VMX_CUENTAS_RETENCION AS b 
				WHERE b.Cuenta =  a.GL_ACCOUNT_ID AND b.Estado = 'True' 
					-- Consiliados
					AND a.ANIO_CONCILIACION = @ANIO AND a.MES_CONCILIACION = @MES AND a.SITE_ID = @SITE_ID
				GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO	,a.GL_ACCOUNT_ID        
				HAVING CASE WHEN SUM(A.RETENCION_MXN_FACT) = 0.01 THEN 0 WHEN SUM(A.RETENCION_MXN_FACT) = -0.01 THEN 0 ELSE SUM(A.RETENCION_MXN_FACT)END < 0

	END
	ELSE
	BEGIN
		-- Obtener todos los movimientos consiliados y no consiliados RETENCION
		INSERT #POLIZASCXP(SITE_ID, BANK_ACCOUNT_ID, CONTROL_NO, VAT_GL_ACCT_ID, DESCRIPCION, TRASLADO, 
			TC_FACTURA, IVA_MXN_TRASLADAR_FACT,RET_MXN_TRASLADAR_FACT, TC_DEPOSITO, IVA_MXN_TRASLADAR_DEP,RET_MXN_TRASLADAR_DEP, PERDIDA_GANANCIA, CUENTA_PER_GANANCIA, FECHA, CLIENTE
			,VOUCHER,VOUCHER_LN,RFC,NAME,AMOUNT,INVOICE_ID)
			SELECT A.SITE_ID
				,A.BANK_ACCOUNT_ID 
				,A.CONTROL_NO 
				,A.GL_ACCOUNT_ID
				,B.DESCRIPCION
				,B.TRASLADO
				,A.TC_FACTURA
				,0
				-- Hacer cero el monto, cuando el Monto de RETENCION prorrateado sea un centavo positivo o negativo.
				,CASE 
					WHEN SUM(A.RETENCION_MXN_FACT) = 0.01 THEN 0 
					WHEN SUM(A.RETENCION_MXN_FACT) = -0.01 THEN 0 
				ELSE SUM(A.RETENCION_MXN_FACT)  END AS RET_MXN_TRASLADAR_FACT
				,A.TC_Pago		
				,0		
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN A.RETENCION_MXN_PAGO + 0.01
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN A.RETENCION_MXN_PAGO - 0.01
				ELSE SUM(A.RETENCION_MXN_PAGO) END AS RET_MXN_TRASLADAR_DEP	
				,CASE 
					WHEN SUM(A.GANANCIA_PERDIDA) = 0.01 THEN 0 
					WHEN SUM(A.GANANCIA_PERDIDA) = -0.01 THEN 0 
				ELSE SUM(A.GANANCIA_PERDIDA)END
				,A.CUENTA_PER_GANANCIA
				,@FECHA
				,A.VENDOR_ID
				,A.VOUCHER_ID
				,A.LINE_NO
				,isnull(V.VAT_REGISTRATION,'')
				,V.NAME
				,A.AMOUNT
				,A.INVOICE_ID
			FROM VMX_CUENTAS_RETENCION AS b,VMX_IVA_TRASL_CXP_03 AS a
			INNER JOIN VENDOR V ON V.ID = A.VENDOR_ID
			WHERE b.Cuenta =  a.GL_ACCOUNT_ID
				AND b.Estado = 'True'
				AND a.ANIO_POSTEO = @ANIO
				AND a.MES_POSTEO = @MES
				AND a.SITE_ID = @SITE_ID
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO,a.GL_ACCOUNT_ID,b.Descripcion,a.TC_FACTURA,b.Traslado,A.RETENCION_MXN_FACT,
				A.TC_Pago,A.RETENCION_MXN_PAGO,A.GANANCIA_PERDIDA,A.CUENTA_PER_GANANCIA,a.VENDOR_ID
				,A.VOUCHER_ID
				,A.LINE_NO
				,V.VAT_REGISTRATION
				,V.NAME
				,A.AMOUNT
				,A.INVOICE_ID
		
		-- Obtener los movimientos con montos negativos RETENCION
		INSERT #POLIZASNEGATIVAS(SITE_ID, BANK_ACCOUNT_ID,CONTROL_NO)
			SELECT A.SITE_ID, A.BANK_ACCOUNT_ID,A.CONTROL_NO      
			FROM VMX_IVA_TRASL_CXP_03 AS a,VMX_DIOTCUENTAS AS b 
			WHERE b.Cuenta =  a.GL_ACCOUNT_ID AND b.Estado = 'True' 
				-- No Consiliados
				AND a.ANIO_POSTEO = @ANIO AND a.MES_POSTEO = @MES AND a.SITE_ID = @SITE_ID
			GROUP BY a.SITE_ID, a.BANK_ACCOUNT_ID,a.CONTROL_NO	,a.GL_ACCOUNT_ID,A.VOUCHER_ID,A.LINE_NO    
			HAVING CASE WHEN SUM(A.RETENCION_MXN_FACT) = 0.01 THEN 0 WHEN SUM(A.RETENCION_MXN_FACT) = -0.01 THEN 0 ELSE SUM(A.RETENCION_MXN_FACT)END < 0
	END		
    
    -- Eliminar las polizas negativas. Filtrar por Banco y No. Control                        
	DELETE FROM #POLIZASCXP 
	FROM #POLIZASCXP AS P LEFT JOIN #POLIZASNEGATIVAS AS N ON P.BANK_ACCOUNT_ID = N.BANK_ACCOUNT_ID AND P.CONTROL_NO = N.CONTROL_NO AND P.SITE_ID = N.SITE_ID
	WHERE N.BANK_ACCOUNT_ID IS NOT NULL AND N.CONTROL_NO IS NOT NULL
	
	-- Eliminar las polizas que han completado el traspaso de RETENCION.
	DELETE FROM #POLIZASCXP
	FROM #POLIZASCXP AS P 
		LEFT JOIN VMX_CONTOLPOLIZA_LINE AS PL 
			ON P.BANK_ACCOUNT_ID = PL.BANK_ACCOUNT_ID AND P.CONTROL_NO = PL.CONTROL_NO AND P.VAT_GL_ACCT_ID = PL.CUENTA AND P.SITE_ID = PL.SITE_ID AND PL.CUSTOMER_ID = P.CLIENTE
	WHERE PL.BANK_ACCOUNT_ID IS NOT NULL AND PL.CONTROL_NO IS NOT NULL AND PL.CUENTA IS NOT NULL
		AND PL.TIPO_OPERACION = 'CXP'
	
	SELECT SITE_ID
		,BANK_ACCOUNT_ID AS Banco
		,CONTROL_NO AS "No. Control"
		,CLIENTE AS Proveedor
		,RFC AS "RFC"
		,NAME AS "Nombre Proveedor"
		,VAT_GL_ACCT_ID AS Cuenta
		,DESCRIPCION AS "Descripción"
		,TRASLADO AS "Cuenta Traslado"
		,VOUCHER AS Voucher
		,VOUCHER_LN AS "Linea Voucher"
		,INVOICE_ID AS Factura
		,AMOUNT AS Monto
		,TC_FACTURA AS "Tipo Cambio Factura"
		,TC_DEPOSITO AS "Tipo Cambio Deposito"
		,ISNULL(IVA_MXN_TRASLADAR_FACT,0.0) AS "IVA Factura"
		,ISNULL(IVA_MXN_TRASLADAR_DEP,0.0) AS "IVA Deposito"
		,ISNULL(RET_MXN_TRASLADAR_FACT,0.0) AS "Retención Factura"
		,ISNULL(RET_MXN_TRASLADAR_DEP,0.0) AS "Retención Deposito"
		,ISNULL(PERDIDA_GANANCIA,0.0) AS "Perdida Ganancia"
		,CUENTA_PER_GANANCIA AS "Cuenta Perdida Ganancia"
		,FECHA AS Fecha
	FROM #POLIZASCXP 
	ORDER BY BANK_ACCOUNT_ID,CONTROL_NO,VOUCHER,VOUCHER_LN


	DROP TABLE #POLIZASCXP                    
	DROP TABLE #POLIZASNEGATIVAS
GO

GRANT EXECUTE ON dbo.PRC_POLIZAS_POR_TRASPASAR_RET_CXP_DET TO PUBLIC
GO