-- Tables

GRANT SELECT, UPDATE, INSERT, DELETE ON VMXCONTROLPOLIZA TO PUBLIC
GRANT SELECT, UPDATE, INSERT, DELETE ON VMX_IVATRASTEMP TO PUBLIC
GRANT SELECT, UPDATE, INSERT, DELETE ON [dbo].[VMX_DATEXTPAGOS] TO PUBLIC
GRANT SELECT, UPDATE, INSERT, DELETE ON [dbo].[VMX_DATEXTPROVEEDOR] TO PUBLIC
GRANT SELECT, UPDATE, INSERT, DELETE ON [dbo].[VMX_CUENTASDESCUENTOSCXC] TO PUBLIC
GRANT SELECT, UPDATE, INSERT, DELETE ON [dbo].[VMX_CONTOLPOLIZA_LINE] TO PUBLIC
GRANT SELECT, UPDATE, INSERT, DELETE ON [dbo].[VMX_IVACUENTASCXC] TO PUBLIC
GRANT SELECT, UPDATE, INSERT, DELETE ON [dbo].[VMX_DIOT_TIPOCAMBIO] TO PUBLIC
GRANT SELECT, UPDATE, INSERT, DELETE ON [dbo].[VMX_CUENTAS_RETENCION] TO PUBLIC
GO

-- Views

GRANT SELECT, INSERT, UPDATE, DELETE ON VMX_IVA_TRASL_CXP_01 TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON VMX_IVA_TRASL_CXP_02 TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.VMX_IVA_TRASL_CXP_03 TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON VMX_IVA_CXC_01 TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON VMX_IVA_CXC_02 TO PUBLIC;
GO

-- Procedures

GRANT EXECUTE ON dbo.PRC_POLIZAS_POR_TRASPASAR_CXP TO PUBLIC
GRANT EXECUTE ON dbo.PRC_POLIZAS_POR_TRASPASAR_CXC TO PUBLIC
GO

GRANT EXECUTE ON dbo.[PRC_POLIZAS_POR_TRASPASAR_RET_CXP] TO PUBLIC
GO
GRANT EXECUTE ON dbo.PRC_POLIZAS_POR_TRASPASAR_CXC_DET TO PUBLIC
GO
GRANT EXECUTE ON dbo.PRC_POLIZAS_POR_TRASPASAR_CXP_DET TO PUBLIC
GO
GRANT EXECUTE ON dbo.PRC_POLIZAS_POR_TRASPASAR_RET_CXP_DET TO PUBLIC
GO

-- Otros

GRANT SELECT, INSERT, UPDATE, DELETE ON NEXT_NUMBER_GEN TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GJ TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GJ_CURR TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GJ_DIST TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GJ_LINE TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GJ_LINE_CURR TO PUBLIC;