

ALTER VIEW [dbo].[VMX_IVA_TRASL_CXP_01]
AS
SELECT     CDL.SITE_ID, CDL.BANK_ACCOUNT_ID, CDL.CONTROL_NO, CD.VENDOR_ID, CD.CHECK_NO, CDL.PCURR_AMOUNT AS Monto_Pago, CDL.AMOUNT AS Monto_Pago2, 
                      CDC.SELL_RATE AS TC_Pago, CDL.SELL_RATE AS TC_Pago2, CD.CURRENCY_ID, CDL.VOUCHER_ID, CD.CLEARED, 
					  YEAR(CD.CLEARED_DATE) AS ANIO_CONCILIACION, MONTH(CD.CLEARED_DATE) AS MES_CONCILIACION,                    
					  YEAR(CD.POSTING_DATE) AS ANIO_POSTEO, MONTH(CD.POSTING_DATE) AS MES_POSTEO,
					  ISNULL(CD.PAYMENT_BATCH_NO,CD.CHECK_NO) AS PAYMENT_NO
FROM         dbo.CASH_DISBURSE_LINE AS CDL INNER JOIN
                      dbo.CASH_DISBURSEMENT AS CD ON CDL.BANK_ACCOUNT_ID = CD.BANK_ACCOUNT_ID AND CDL.CONTROL_NO = CD.CONTROL_NO INNER JOIN
                      dbo.CASH_DISBURSE_CURR AS CDC ON CD.BANK_ACCOUNT_ID = CDC.BANK_ACCOUNT_ID AND CD.CONTROL_NO = CDC.CONTROL_NO AND 
                      CD.CURRENCY_ID = CDC.CURRENCY_ID
WHERE     (CDL.VOUCHER_ID IS NOT NULL) AND (CD.STATUS <> 'X')



GO


